package projects

import (
	"bytes"
	"context"
	"encoding/json"
	"fmt"
	"mime/multipart"
	"net/http"

	twapi "github.com/teamwork/twapi-go-sdk"
)

var (
	_ twapi.HTTPRequester = (*PendingFileCreateRequest)(nil)
	_ twapi.HTTPResponser = (*PendingFileCreateResponse)(nil)
)

// PendingFileRef is the handle the API issues for a file that has been uploaded
// but is not yet attached to anything. Treat it as opaque: it is a token to pass
// back, not a value to parse. The format is not stable across upload methods,
// for example the file extension is appended by some of them and not by others.
//
// A reference is scoped to the installation, does not expire, and is consumed
// the first time it is attached to something. Attaching the same reference twice
// fails with "Temporary file reference not found".
//
// References are produced by PendingFileCreate and consumed by the attachment
// fields on tasks, comments and messages.
type PendingFileRef string

// PendingFileCreateRequest represents the request body for uploading a file.
// The file is stored on its own, and a later request attaches it to a task, a
// comment or a message.
//
// https://apidocs.teamwork.com/docs/teamwork/v1/file-uploading/post-pendingfiles-json
type PendingFileCreateRequest struct {
	// FileName is the name of the file, including its extension. The API decides
	// the stored file's content type from the extension, so a name without one is
	// harder for the recipient to open.
	FileName string

	// Contents is the file body.
	//
	// This is a byte slice rather than an io.Reader because a multipart body has
	// to be assembled in full before it is sent, so a reader would be drained
	// into a buffer anyway. Holding the bytes keeps the request re-executable,
	// which the rest of the SDK assumes: a request value can be executed more
	// than once, and a drained reader would silently upload an empty file the
	// second time. Read a file in with os.ReadFile.
	Contents []byte
}

// NewPendingFileCreateRequest creates a new PendingFileCreateRequest with the
// provided required fields.
func NewPendingFileCreateRequest(fileName string, contents []byte) PendingFileCreateRequest {
	return PendingFileCreateRequest{
		FileName: fileName,
		Contents: contents,
	}
}

// HTTPRequest creates an HTTP request for the PendingFileCreateRequest. Unlike
// every other request in this package the body is multipart/form-data rather
// than JSON, since this endpoint carries the file itself.
func (p PendingFileCreateRequest) HTTPRequest(ctx context.Context, server string) (*http.Request, error) {
	switch {
	case p.FileName == "":
		return nil, fmt.Errorf("pending file requires a file name")
	case len(p.Contents) == 0:
		return nil, fmt.Errorf("pending file requires the file contents")
	}

	// Unlike the other v1 routes in this package, which hang off the bare server
	// root, this upload endpoint genuinely lives under /projects/api/v1/.
	uri := server + "/projects/api/v1/pendingfiles.json"

	var body bytes.Buffer
	// The file bytes dominate the body; the multipart framing (boundary plus the
	// part headers and CRLFs) is a couple hundred bytes, so presizing turns the
	// assembly into a single allocation and copy.
	body.Grow(len(p.Contents) + 512)
	writer := multipart.NewWriter(&body)
	part, err := writer.CreateFormFile("file", p.FileName)
	if err != nil {
		return nil, fmt.Errorf("failed to encode create pending file request: %w", err)
	}
	if _, err := part.Write(p.Contents); err != nil {
		return nil, fmt.Errorf("failed to encode create pending file request: %w", err)
	}
	if err := writer.Close(); err != nil {
		return nil, fmt.Errorf("failed to encode create pending file request: %w", err)
	}

	req, err := http.NewRequestWithContext(ctx, http.MethodPost, uri, &body)
	if err != nil {
		return nil, err
	}
	// The boundary is generated by the writer, so the content type has to come
	// from it as well.
	req.Header.Set("Content-Type", writer.FormDataContentType())

	return req, nil
}

// PendingFileCreateResponse represents the response body for uploading a file.
//
// https://apidocs.teamwork.com/docs/teamwork/v1/file-uploading/post-pendingfiles-json
type PendingFileCreateResponse struct {
	// PendingFile contains the reference of the uploaded file.
	PendingFile struct {
		// Ref identifies the uploaded file until it is attached to something.
		Ref PendingFileRef `json:"ref"`
	} `json:"pendingFile"`
}

// HandleHTTPResponse handles the HTTP response for the
// PendingFileCreateResponse. If some unexpected HTTP status code is returned by
// the API, a twapi.HTTPError is returned.
func (p *PendingFileCreateResponse) HandleHTTPResponse(resp *http.Response) error {
	if resp.StatusCode != http.StatusCreated {
		return twapi.NewHTTPError(resp, "failed to create pending file")
	}
	if err := json.NewDecoder(resp.Body).Decode(p); err != nil {
		return fmt.Errorf("failed to decode create pending file response: %w", err)
	}
	if p.PendingFile.Ref == "" {
		return fmt.Errorf("create pending file response does not contain a valid identifier")
	}
	return nil
}

// PendingFileCreate uploads a file using the provided request and returns the
// response. The reference in the response identifies a file that is not attached
// to anything yet; attaching it is a separate operation on whichever entity
// should own the file.
func PendingFileCreate(
	ctx context.Context,
	engine *twapi.Engine,
	req PendingFileCreateRequest,
) (*PendingFileCreateResponse, error) {
	return twapi.Execute[PendingFileCreateRequest, *PendingFileCreateResponse](ctx, engine, req)
}
