// Code generated by sparsefieldsgen; DO NOT EDIT.

package projects

import (
	"net/url"

	twapi "github.com/teamwork/twapi-go-sdk"
)

// ActivityField identifies a JSON-tagged attribute of Activity usable for v3 sparse fieldsets.
type ActivityField string

// List of possible Activity fields.
const (
	ActivityFieldID               ActivityField = "id"
	ActivityFieldAction           ActivityField = "activityType"
	ActivityFieldLatestAction     ActivityField = "latestActivityType"
	ActivityFieldAt               ActivityField = "dateTime"
	ActivityFieldDescription      ActivityField = "description"
	ActivityFieldExtraDescription ActivityField = "extraDescription"
	ActivityFieldPublicInfo       ActivityField = "publicInfo"
	ActivityFieldDueAt            ActivityField = "dueDate"
	ActivityFieldForUserName      ActivityField = "forUserName"
	ActivityFieldItemLink         ActivityField = "itemLink"
	ActivityFieldLink             ActivityField = "link"
	ActivityFieldUser             ActivityField = "user"
	ActivityFieldForUser          ActivityField = "forUser"
	ActivityFieldProject          ActivityField = "project"
	ActivityFieldCompany          ActivityField = "company"
	ActivityFieldItem             ActivityField = "item"
)

// AllocationField identifies a JSON-tagged attribute of Allocation usable for v3 sparse fieldsets.
type AllocationField string

// List of possible Allocation fields.
const (
	AllocationFieldID                      AllocationField = "id"
	AllocationFieldInstallation            AllocationField = "installation"
	AllocationFieldInstallationID          AllocationField = "installationId"
	AllocationFieldProject                 AllocationField = "project"
	AllocationFieldProjectID               AllocationField = "projectId"
	AllocationFieldAssignedUser            AllocationField = "assignedUser"
	AllocationFieldAssignedUserID          AllocationField = "assignedUserID"
	AllocationFieldTitle                   AllocationField = "title"
	AllocationFieldDescription             AllocationField = "description"
	AllocationFieldStartDate               AllocationField = "startedAt"
	AllocationFieldEndDate                 AllocationField = "endedAt"
	AllocationFieldDuration                AllocationField = "duration"
	AllocationFieldAvailableDuration       AllocationField = "availableDuration"
	AllocationFieldAllocatedDuration       AllocationField = "allocatedDuration"
	AllocationFieldHoursPerDay             AllocationField = "hoursPerDay"
	AllocationFieldSecondsPerDay           AllocationField = "secondsPerDay"
	AllocationFieldColor                   AllocationField = "color"
	AllocationFieldStatus                  AllocationField = "status"
	AllocationFieldDistributeType          AllocationField = "distributeType"
	AllocationFieldIsBillable              AllocationField = "isBillable"
	AllocationFieldOverAllocated           AllocationField = "overAllocated"
	AllocationFieldRecurringRule           AllocationField = "recurringRule"
	AllocationFieldLinkedTaskIDs           AllocationField = "linkedTaskIDs"
	AllocationFieldLinkedTaskLoggedTime    AllocationField = "linkedTaskLoggedTime"
	AllocationFieldLinkedTaskEstimatedTime AllocationField = "linkedTaskEstimatedTime"
	AllocationFieldFinancialDetails        AllocationField = "financialDetails"
	AllocationFieldCanViewFinancialDetails AllocationField = "canViewFinancialDetails"
	AllocationFieldCreatedAt               AllocationField = "createdAt"
	AllocationFieldCreatedBy               AllocationField = "createdBy"
	AllocationFieldUpdatedAt               AllocationField = "updatedAt"
	AllocationFieldUpdatedBy               AllocationField = "updatedBy"
	AllocationFieldDeletedAt               AllocationField = "deletedAt"
	AllocationFieldDeletedBy               AllocationField = "deletedBy"
)

// CalendarEventField identifies a JSON-tagged attribute of CalendarEvent usable for v3 sparse fieldsets.
type CalendarEventField string

// List of possible CalendarEvent fields.
const (
	CalendarEventFieldID                      CalendarEventField = "id"
	CalendarEventFieldSummary                 CalendarEventField = "summary"
	CalendarEventFieldDescription             CalendarEventField = "description"
	CalendarEventFieldOrganizer               CalendarEventField = "organizer"
	CalendarEventFieldEventCreator            CalendarEventField = "eventCreator"
	CalendarEventFieldStart                   CalendarEventField = "start"
	CalendarEventFieldEnd                     CalendarEventField = "end"
	CalendarEventFieldAllDay                  CalendarEventField = "allDay"
	CalendarEventFieldLocation                CalendarEventField = "location"
	CalendarEventFieldType                    CalendarEventField = "type"
	CalendarEventFieldRecurrence              CalendarEventField = "recurrence"
	CalendarEventFieldGuestsCanInviteOthers   CalendarEventField = "guestsCanInviteOthers"
	CalendarEventFieldGuestsCanModify         CalendarEventField = "guestsCanModify"
	CalendarEventFieldGuestsCanSeeOtherGuests CalendarEventField = "guestsCanSeeOtherGuests"
	CalendarEventFieldTransparency            CalendarEventField = "transparency"
	CalendarEventFieldVisibility              CalendarEventField = "visibility"
	CalendarEventFieldVideoCallLink           CalendarEventField = "videoCallLink"
	CalendarEventFieldCalOwnerCanEdit         CalendarEventField = "calOwnerCanEdit"
	CalendarEventFieldTimeblock               CalendarEventField = "timeblock"
	CalendarEventFieldAttendees               CalendarEventField = "attendees"
	CalendarEventFieldAttendeesOmitted        CalendarEventField = "attendeesOmitted"
	CalendarEventFieldCalendar                CalendarEventField = "calendar"
	CalendarEventFieldStatus                  CalendarEventField = "status"
	CalendarEventFieldCreatedBy               CalendarEventField = "createdBy"
	CalendarEventFieldCreatedAt               CalendarEventField = "createdAt"
	CalendarEventFieldUpdatedAt               CalendarEventField = "updatedAt"
)

// CalendarField identifies a JSON-tagged attribute of Calendar usable for v3 sparse fieldsets.
type CalendarField string

// List of possible Calendar fields.
const (
	CalendarFieldID        CalendarField = "id"
	CalendarFieldName      CalendarField = "name"
	CalendarFieldType      CalendarField = "type"
	CalendarFieldCreatedAt CalendarField = "createdAt"
	CalendarFieldUpdatedAt CalendarField = "updatedAt"
)

// CommentField identifies a JSON-tagged attribute of Comment usable for v3 sparse fieldsets.
type CommentField string

// List of possible Comment fields.
const (
	CommentFieldID           CommentField = "id"
	CommentFieldBody         CommentField = "body"
	CommentFieldHTMLBody     CommentField = "htmlBody"
	CommentFieldContentType  CommentField = "contentType"
	CommentFieldObject       CommentField = "object"
	CommentFieldProject      CommentField = "project"
	CommentFieldPostedBy     CommentField = "postedBy"
	CommentFieldPostedAt     CommentField = "postedDateTime"
	CommentFieldLastEditedBy CommentField = "lastEditedBy"
	CommentFieldEditedAt     CommentField = "dateLastEdited"
	CommentFieldDeleted      CommentField = "deleted"
	CommentFieldDeletedBy    CommentField = "deletedBy"
	CommentFieldDeletedAt    CommentField = "dateDeleted"
)

// CommentSideloadField identifies a JSON-tagged attribute of CommentSideload usable for v3 sparse fieldsets.
type CommentSideloadField string

// List of possible CommentSideload fields.
const (
	CommentSideloadFieldID       CommentSideloadField = "id"
	CommentSideloadFieldBody     CommentSideloadField = "title"
	CommentSideloadFieldObject   CommentSideloadField = "object"
	CommentSideloadFieldProject  CommentSideloadField = "project"
	CommentSideloadFieldPostedBy CommentSideloadField = "postedBy"
	CommentSideloadFieldPostedAt CommentSideloadField = "postedDateTime"
)

// CompanyField identifies a JSON-tagged attribute of Company usable for v3 sparse fieldsets.
type CompanyField string

// List of possible Company fields.
const (
	CompanyFieldID          CompanyField = "id"
	CompanyFieldAddressOne  CompanyField = "addressOne"
	CompanyFieldAddressTwo  CompanyField = "addressTwo"
	CompanyFieldCity        CompanyField = "city"
	CompanyFieldCountryCode CompanyField = "countryCode"
	CompanyFieldEmailOne    CompanyField = "emailOne"
	CompanyFieldEmailTwo    CompanyField = "emailTwo"
	CompanyFieldEmailThree  CompanyField = "emailThree"
	CompanyFieldFax         CompanyField = "fax"
	CompanyFieldName        CompanyField = "name"
	CompanyFieldPhone       CompanyField = "phone"
	CompanyFieldProfile     CompanyField = "profileText"
	CompanyFieldState       CompanyField = "state"
	CompanyFieldWebsite     CompanyField = "website"
	CompanyFieldZip         CompanyField = "zip"
	CompanyFieldManagedBy   CompanyField = "clientManagedBy"
	CompanyFieldIndustry    CompanyField = "industry"
	CompanyFieldTags        CompanyField = "tags"
	CompanyFieldCreatedAt   CompanyField = "createdAt"
	CompanyFieldUpdatedAt   CompanyField = "updatedAt"
	CompanyFieldStatus      CompanyField = "status"
)

// CustomFieldField identifies a JSON-tagged attribute of CustomField usable for v3 sparse fieldsets.
type CustomFieldField string

// List of possible CustomField fields.
const (
	CustomFieldFieldOptions      CustomFieldField = "options"
	CustomFieldFieldID           CustomFieldField = "id"
	CustomFieldFieldName         CustomFieldField = "name"
	CustomFieldFieldDescription  CustomFieldField = "description"
	CustomFieldFieldType         CustomFieldField = "type"
	CustomFieldFieldEntity       CustomFieldField = "entity"
	CustomFieldFieldRequired     CustomFieldField = "required"
	CustomFieldFieldFormula      CustomFieldField = "formula"
	CustomFieldFieldCurrencyCode CustomFieldField = "currencyCode"
	CustomFieldFieldUnit         CustomFieldField = "unitId"
	CustomFieldFieldProject      CustomFieldField = "project"
	CustomFieldFieldCreatedBy    CustomFieldField = "createdBy"
	CustomFieldFieldCreatedAt    CustomFieldField = "createdAt"
	CustomFieldFieldUpdatedBy    CustomFieldField = "updatedBy"
	CustomFieldFieldUpdatedAt    CustomFieldField = "updatedAt"
	CustomFieldFieldDeleted      CustomFieldField = "deleted"
	CustomFieldFieldDeletedBy    CustomFieldField = "deletedBy"
	CustomFieldFieldDeletedAt    CustomFieldField = "deletedAt"
)

// CustomFieldValueField identifies a JSON-tagged attribute of CustomFieldValue usable for v3 sparse fieldsets.
type CustomFieldValueField string

// List of possible CustomFieldValue fields.
const (
	CustomFieldValueFieldID           CustomFieldValueField = "id"
	CustomFieldValueFieldValue        CustomFieldValueField = "value"
	CustomFieldValueFieldCurrencyCode CustomFieldValueField = "currencySymbol"
	CustomFieldValueFieldCountryCode  CustomFieldValueField = "countryCode"
	CustomFieldValueFieldCustomField  CustomFieldValueField = "customfield"
	CustomFieldValueFieldTask         CustomFieldValueField = "task"
	CustomFieldValueFieldProject      CustomFieldValueField = "project"
	CustomFieldValueFieldCompany      CustomFieldValueField = "company"
	CustomFieldValueFieldCreatedBy    CustomFieldValueField = "createdBy"
	CustomFieldValueFieldCreatedAt    CustomFieldValueField = "createdAt"
	CustomFieldValueFieldUpdatedBy    CustomFieldValueField = "updatedBy"
	CustomFieldValueFieldUpdatedAt    CustomFieldValueField = "updatedAt"
)

// JobRoleField identifies a JSON-tagged attribute of JobRole usable for v3 sparse fieldsets.
type JobRoleField string

// List of possible JobRole fields.
const (
	JobRoleFieldID              JobRoleField = "id"
	JobRoleFieldName            JobRoleField = "name"
	JobRoleFieldIsActive        JobRoleField = "isActive"
	JobRoleFieldCreatedByUserID JobRoleField = "createdByUser"
	JobRoleFieldCreatedAt       JobRoleField = "createdAt"
	JobRoleFieldUpdatedByUserID JobRoleField = "updatedByUser"
	JobRoleFieldUpdatedAt       JobRoleField = "updatedAt"
	JobRoleFieldDeletedByUserID JobRoleField = "deletedByUser"
	JobRoleFieldDeletedAt       JobRoleField = "deletedAt"
	JobRoleFieldUsers           JobRoleField = "users"
	JobRoleFieldPrimaryUsers    JobRoleField = "primaryUsers"
)

// LinkField identifies a JSON-tagged attribute of Link usable for v3 sparse fieldsets.
type LinkField string

// List of possible Link fields.
const (
	LinkFieldID              LinkField = "id"
	LinkFieldTitle           LinkField = "name"
	LinkFieldDescription     LinkField = "description"
	LinkFieldCode            LinkField = "code"
	LinkFieldProjectID       LinkField = "project-id"
	LinkFieldTags            LinkField = "tags"
	LinkFieldCreatedByUserID LinkField = "created-by-userId"
	LinkFieldCreatedAt       LinkField = "created-date"
	LinkFieldUpdatedByUserID LinkField = "updated-by-userId"
	LinkFieldUpdatedAt       LinkField = "updated-date"
)

// MessageField identifies a JSON-tagged attribute of Message usable for v3 sparse fieldsets.
type MessageField string

// List of possible Message fields.
const (
	MessageFieldID              MessageField = "id"
	MessageFieldTitle           MessageField = "title"
	MessageFieldProject         MessageField = "project"
	MessageFieldTags            MessageField = "tags"
	MessageFieldLastReply       MessageField = "lastReply"
	MessageFieldLastReplyStatus MessageField = "replyStatus"
	MessageFieldStatus          MessageField = "status"
	MessageFieldBody            MessageField = "body"
	MessageFieldAuthor          MessageField = "author"
	MessageFieldMessage         MessageField = "message"
	MessageFieldMeta            MessageField = "meta"
	MessageFieldCreatedAt       MessageField = "createdAt"
	MessageFieldUpdatedAt       MessageField = "updatedAt"
)

// MessageReplyField identifies a JSON-tagged attribute of MessageReply usable for v3 sparse fieldsets.
type MessageReplyField string

// List of possible MessageReply fields.
const (
	MessageReplyFieldID        MessageReplyField = "id"
	MessageReplyFieldBody      MessageReplyField = "body"
	MessageReplyFieldAuthor    MessageReplyField = "author"
	MessageReplyFieldMessage   MessageReplyField = "message"
	MessageReplyFieldMeta      MessageReplyField = "meta"
	MessageReplyFieldCreatedAt MessageReplyField = "createdAt"
	MessageReplyFieldUpdatedAt MessageReplyField = "updatedAt"
	MessageReplyFieldStatus    MessageReplyField = "status"
)

// MilestoneField identifies a JSON-tagged attribute of Milestone usable for v3 sparse fieldsets.
type MilestoneField string

// List of possible Milestone fields.
const (
	MilestoneFieldID                 MilestoneField = "id"
	MilestoneFieldName               MilestoneField = "name"
	MilestoneFieldDescription        MilestoneField = "description"
	MilestoneFieldDueAt              MilestoneField = "deadline"
	MilestoneFieldProject            MilestoneField = "project"
	MilestoneFieldTasklists          MilestoneField = "tasklists"
	MilestoneFieldTags               MilestoneField = "tags"
	MilestoneFieldResponsibleParties MilestoneField = "responsibleParties"
	MilestoneFieldCreatedAt          MilestoneField = "createdOn"
	MilestoneFieldUpdatedAt          MilestoneField = "lastChangedOn"
	MilestoneFieldDeletedAt          MilestoneField = "deletedOn"
	MilestoneFieldCompletedAt        MilestoneField = "completedOn"
	MilestoneFieldCompletedBy        MilestoneField = "completedBy"
	MilestoneFieldCompleted          MilestoneField = "completed"
	MilestoneFieldStatus             MilestoneField = "status"
)

// NotebookField identifies a JSON-tagged attribute of Notebook usable for v3 sparse fieldsets.
type NotebookField string

// List of possible Notebook fields.
const (
	NotebookFieldID          NotebookField = "id"
	NotebookFieldName        NotebookField = "name"
	NotebookFieldDescription NotebookField = "description"
	NotebookFieldContents    NotebookField = "contents"
	NotebookFieldType        NotebookField = "type"
	NotebookFieldProject     NotebookField = "project"
	NotebookFieldTags        NotebookField = "tags"
	NotebookFieldCreatedAt   NotebookField = "createdAt"
	NotebookFieldCreatedBy   NotebookField = "createdBy"
	NotebookFieldUpdatedAt   NotebookField = "updatedAt"
	NotebookFieldUpdatedBy   NotebookField = "updatedBy"
	NotebookFieldDeletedAt   NotebookField = "deletedAt"
	NotebookFieldDeletedBy   NotebookField = "deletedBy"
	NotebookFieldDeleted     NotebookField = "deleted"
)

// ProjectBudgetField identifies a JSON-tagged attribute of ProjectBudget usable for v3 sparse fieldsets.
type ProjectBudgetField string

// List of possible ProjectBudget fields.
const (
	ProjectBudgetFieldID                 ProjectBudgetField = "id"
	ProjectBudgetFieldProjectID          ProjectBudgetField = "projectId"
	ProjectBudgetFieldType               ProjectBudgetField = "type"
	ProjectBudgetFieldStatus             ProjectBudgetField = "status"
	ProjectBudgetFieldCapacity           ProjectBudgetField = "capacity"
	ProjectBudgetFieldCapacityUsed       ProjectBudgetField = "capacityUsed"
	ProjectBudgetFieldOriginatorBudgetID ProjectBudgetField = "originatorBudgetId"
	ProjectBudgetFieldIsRepeating        ProjectBudgetField = "isRepeating"
	ProjectBudgetFieldRepeatPeriod       ProjectBudgetField = "repeatPeriod"
	ProjectBudgetFieldRepeatUnit         ProjectBudgetField = "repeatUnit"
	ProjectBudgetFieldRepeatsRemaining   ProjectBudgetField = "repeatsRemaining"
	ProjectBudgetFieldSequenceNumber     ProjectBudgetField = "sequenceNumber"
	ProjectBudgetFieldStartDateTime      ProjectBudgetField = "startDateTime"
	ProjectBudgetFieldEndDateTime        ProjectBudgetField = "endDateTime"
	ProjectBudgetFieldCurrencyCode       ProjectBudgetField = "currencyCode"
	ProjectBudgetFieldTimelogType        ProjectBudgetField = "timelogType"
	ProjectBudgetFieldExpenseType        ProjectBudgetField = "expenseType"
	ProjectBudgetFieldDefaultRate        ProjectBudgetField = "defaultRate"
	ProjectBudgetFieldNotificationIDs    ProjectBudgetField = "notificationIds"
	ProjectBudgetFieldCreatedBy          ProjectBudgetField = "createdByUserId"
	ProjectBudgetFieldCreatedAt          ProjectBudgetField = "dateCreated"
	ProjectBudgetFieldUpdatedBy          ProjectBudgetField = "updatedBy"
	ProjectBudgetFieldUpdatedAt          ProjectBudgetField = "dateUpdated"
	ProjectBudgetFieldCompletedBy        ProjectBudgetField = "completedByUserId"
	ProjectBudgetFieldCompletedAt        ProjectBudgetField = "dateCompleted"
	ProjectBudgetFieldDeletedBy          ProjectBudgetField = "deletedByUserId"
	ProjectBudgetFieldDeletedAt          ProjectBudgetField = "dateDeleted"
)

// ProjectCategoryField identifies a JSON-tagged attribute of ProjectCategory usable for v3 sparse fieldsets.
type ProjectCategoryField string

// List of possible ProjectCategory fields.
const (
	ProjectCategoryFieldID     ProjectCategoryField = "id"
	ProjectCategoryFieldName   ProjectCategoryField = "name"
	ProjectCategoryFieldColor  ProjectCategoryField = "color"
	ProjectCategoryFieldParent ProjectCategoryField = "parent"
	ProjectCategoryFieldCount  ProjectCategoryField = "count"
)

// ProjectField identifies a JSON-tagged attribute of Project usable for v3 sparse fieldsets.
type ProjectField string

// List of possible Project fields.
const (
	ProjectFieldID           ProjectField = "id"
	ProjectFieldDescription  ProjectField = "description"
	ProjectFieldName         ProjectField = "name"
	ProjectFieldStartAt      ProjectField = "startAt"
	ProjectFieldEndAt        ProjectField = "endAt"
	ProjectFieldCategory     ProjectField = "category"
	ProjectFieldCompany      ProjectField = "company"
	ProjectFieldOwner        ProjectField = "projectOwner"
	ProjectFieldTags         ProjectField = "tags"
	ProjectFieldLastWorkedAt ProjectField = "lastWorkedOn"
	ProjectFieldCreatedAt    ProjectField = "createdAt"
	ProjectFieldCreatedBy    ProjectField = "createdBy"
	ProjectFieldUpdatedAt    ProjectField = "updatedAt"
	ProjectFieldUpdatedBy    ProjectField = "updatedBy"
	ProjectFieldCompletedAt  ProjectField = "completedAt"
	ProjectFieldCompletedBy  ProjectField = "completedBy"
	ProjectFieldStatus       ProjectField = "status"
	ProjectFieldIsBillable   ProjectField = "isBillable"
	ProjectFieldType         ProjectField = "type"
)

// SkillField identifies a JSON-tagged attribute of Skill usable for v3 sparse fieldsets.
type SkillField string

// List of possible Skill fields.
const (
	SkillFieldID              SkillField = "id"
	SkillFieldName            SkillField = "name"
	SkillFieldCreatedByUserID SkillField = "createdByUser"
	SkillFieldCreatedAt       SkillField = "createdAt"
	SkillFieldUpdatedByUserID SkillField = "updatedByUser"
	SkillFieldUpdatedAt       SkillField = "updatedAt"
	SkillFieldDeletedByUserID SkillField = "deletedByUser"
	SkillFieldDeletedAt       SkillField = "deletedAt"
	SkillFieldUsers           SkillField = "users"
)

// TagField identifies a JSON-tagged attribute of Tag usable for v3 sparse fieldsets.
type TagField string

// List of possible Tag fields.
const (
	TagFieldID      TagField = "id"
	TagFieldName    TagField = "name"
	TagFieldColor   TagField = "color"
	TagFieldProject TagField = "project"
)

// TaskField identifies a JSON-tagged attribute of Task usable for v3 sparse fieldsets.
type TaskField string

// List of possible Task fields.
const (
	TaskFieldID                     TaskField = "id"
	TaskFieldName                   TaskField = "name"
	TaskFieldDescription            TaskField = "description"
	TaskFieldDescriptionContentType TaskField = "descriptionContentType"
	TaskFieldPriority               TaskField = "priority"
	TaskFieldProgress               TaskField = "progress"
	TaskFieldStartAt                TaskField = "startDate"
	TaskFieldDueAt                  TaskField = "dueDate"
	TaskFieldEstimatedMinutes       TaskField = "estimateMinutes"
	TaskFieldTasklist               TaskField = "tasklist"
	TaskFieldParentTask             TaskField = "parentTask"
	TaskFieldAssignees              TaskField = "assignees"
	TaskFieldTags                   TaskField = "tags"
	TaskFieldPredecessors           TaskField = "predecessors"
	TaskFieldWorkflowStages         TaskField = "workflowStages"
	TaskFieldCreatedBy              TaskField = "createdBy"
	TaskFieldCreatedAt              TaskField = "createdAt"
	TaskFieldUpdatedBy              TaskField = "updatedBy"
	TaskFieldUpdatedAt              TaskField = "updatedAt"
	TaskFieldDeletedBy              TaskField = "deletedBy"
	TaskFieldDeletedAt              TaskField = "deletedAt"
	TaskFieldCompletedBy            TaskField = "completedBy"
	TaskFieldCompletedAt            TaskField = "completedAt"
	TaskFieldStatus                 TaskField = "status"
)

// TasklistBudgetField identifies a JSON-tagged attribute of TasklistBudget usable for v3 sparse fieldsets.
type TasklistBudgetField string

// List of possible TasklistBudget fields.
const (
	TasklistBudgetFieldID            TasklistBudgetField = "id"
	TasklistBudgetFieldType          TasklistBudgetField = "type"
	TasklistBudgetFieldCapacity      TasklistBudgetField = "capacity"
	TasklistBudgetFieldCapacityUsed  TasklistBudgetField = "capacityUsed"
	TasklistBudgetFieldProjectID     TasklistBudgetField = "projectId"
	TasklistBudgetFieldProjectBudget TasklistBudgetField = "projectbudget"
	TasklistBudgetFieldTasklist      TasklistBudgetField = "tasklist"
	TasklistBudgetFieldMilestone     TasklistBudgetField = "milestone"
	TasklistBudgetFieldNotifications TasklistBudgetField = "notifications"
	TasklistBudgetFieldCreatedAt     TasklistBudgetField = "createdAt"
	TasklistBudgetFieldCreatedBy     TasklistBudgetField = "createdBy"
	TasklistBudgetFieldUpdatedAt     TasklistBudgetField = "updatedAt"
	TasklistBudgetFieldUpdatedBy     TasklistBudgetField = "updatedBy"
	TasklistBudgetFieldDeletedAt     TasklistBudgetField = "deletedAt"
	TasklistBudgetFieldDeletedBy     TasklistBudgetField = "deletedBy"
)

// TasklistBudgetNotificationField identifies a JSON-tagged attribute of TasklistBudgetNotification usable for v3 sparse fieldsets.
type TasklistBudgetNotificationField string

// List of possible TasklistBudgetNotification fields.
const (
	TasklistBudgetNotificationFieldID                 TasklistBudgetNotificationField = "id"
	TasklistBudgetNotificationFieldBudgetID           TasklistBudgetNotificationField = "budgetId"
	TasklistBudgetNotificationFieldCapacityThreshold  TasklistBudgetNotificationField = "capacityThreshold"
	TasklistBudgetNotificationFieldNotificationMedium TasklistBudgetNotificationField = "notificationMedium"
	TasklistBudgetNotificationFieldUserID             TasklistBudgetNotificationField = "userId"
	TasklistBudgetNotificationFieldTeamID             TasklistBudgetNotificationField = "teamId"
	TasklistBudgetNotificationFieldCompanyID          TasklistBudgetNotificationField = "companyId"
)

// TasklistField identifies a JSON-tagged attribute of Tasklist usable for v3 sparse fieldsets.
type TasklistField string

// List of possible Tasklist fields.
const (
	TasklistFieldID          TasklistField = "id"
	TasklistFieldName        TasklistField = "name"
	TasklistFieldDescription TasklistField = "description"
	TasklistFieldProject     TasklistField = "project"
	TasklistFieldMilestone   TasklistField = "milestone"
	TasklistFieldCreatedAt   TasklistField = "createdAt"
	TasklistFieldUpdatedAt   TasklistField = "updatedAt"
	TasklistFieldStatus      TasklistField = "status"
)

// TeamField identifies a JSON-tagged attribute of Team usable for v3 sparse fieldsets.
type TeamField string

// List of possible Team fields.
const (
	TeamFieldID          TeamField = "id"
	TeamFieldName        TeamField = "name"
	TeamFieldDescription TeamField = "description"
	TeamFieldHandle      TeamField = "handle"
	TeamFieldLogoURL     TeamField = "logoUrl"
	TeamFieldLogoIcon    TeamField = "logoIcon"
	TeamFieldLogoColor   TeamField = "logoColor"
	TeamFieldProjectID   TeamField = "projectId"
	TeamFieldCompany     TeamField = "company"
	TeamFieldParentTeam  TeamField = "parentTeam"
	TeamFieldRootTeam    TeamField = "rootTeam"
	TeamFieldMembers     TeamField = "members"
	TeamFieldCreatedBy   TeamField = "createdByUserId"
	TeamFieldCreatedAt   TeamField = "dateCreated"
	TeamFieldUpdatedBy   TeamField = "updatedByUserId"
	TeamFieldUpdatedAt   TeamField = "dateUpdated"
	TeamFieldDeleted     TeamField = "deleted"
	TeamFieldDeletedAt   TeamField = "deletedDate"
)

// TimelogField identifies a JSON-tagged attribute of Timelog usable for v3 sparse fieldsets.
type TimelogField string

// List of possible Timelog fields.
const (
	TimelogFieldID           TimelogField = "id"
	TimelogFieldDescription  TimelogField = "description"
	TimelogFieldBillable     TimelogField = "billable"
	TimelogFieldMinutes      TimelogField = "minutes"
	TimelogFieldLoggedAt     TimelogField = "timeLogged"
	TimelogFieldUser         TimelogField = "user"
	TimelogFieldTask         TimelogField = "task"
	TimelogFieldProject      TimelogField = "project"
	TimelogFieldTags         TimelogField = "tags"
	TimelogFieldDeskTicketID TimelogField = "deskTicketId"
	TimelogFieldCreatedAt    TimelogField = "createdAt"
	TimelogFieldLoggedBy     TimelogField = "loggedBy"
	TimelogFieldUpdatedAt    TimelogField = "updatedAt"
	TimelogFieldUpdatedBy    TimelogField = "updatedBy"
	TimelogFieldDeletedAt    TimelogField = "deletedAt"
	TimelogFieldDeletedBy    TimelogField = "deletedBy"
	TimelogFieldDeleted      TimelogField = "deleted"
)

// TimerField identifies a JSON-tagged attribute of Timer usable for v3 sparse fieldsets.
type TimerField string

// List of possible Timer fields.
const (
	TimerFieldID             TimerField = "id"
	TimerFieldDescription    TimerField = "description"
	TimerFieldRunning        TimerField = "running"
	TimerFieldBillable       TimerField = "billable"
	TimerFieldUser           TimerField = "user"
	TimerFieldTask           TimerField = "task"
	TimerFieldProject        TimerField = "project"
	TimerFieldTimelog        TimerField = "timelog"
	TimerFieldCreatedAt      TimerField = "createdAt"
	TimerFieldUpdatedAt      TimerField = "updatedAt"
	TimerFieldDeletedAt      TimerField = "deletedAt"
	TimerFieldDeleted        TimerField = "deleted"
	TimerFieldDuration       TimerField = "duration"
	TimerFieldLastStartedAt  TimerField = "lastStartedAt"
	TimerFieldLastIntervalAt TimerField = "timerLastIntervalEnd"
	TimerFieldIntervals      TimerField = "intervals"
)

// UserField identifies a JSON-tagged attribute of User usable for v3 sparse fieldsets.
type UserField string

// List of possible User fields.
const (
	UserFieldID          UserField = "id"
	UserFieldFirstName   UserField = "firstName"
	UserFieldLastName    UserField = "lastName"
	UserFieldTitle       UserField = "title"
	UserFieldEmail       UserField = "email"
	UserFieldAdmin       UserField = "isAdmin"
	UserFieldType        UserField = "type"
	UserFieldCost        UserField = "userCost"
	UserFieldRate        UserField = "userRate"
	UserFieldCompany     UserField = "company"
	UserFieldJobRoles    UserField = "jobRoles"
	UserFieldSkills      UserField = "skills"
	UserFieldWorkingHour UserField = "workingHour"
	UserFieldLengthOfDay UserField = "lengthOfDay"
	UserFieldDeleted     UserField = "deleted"
	UserFieldCreatedBy   UserField = "createdBy"
	UserFieldCreatedAt   UserField = "createdAt"
	UserFieldUpdatedBy   UserField = "updatedBy"
	UserFieldUpdatedAt   UserField = "updatedAt"
)

// WorkflowField identifies a JSON-tagged attribute of Workflow usable for v3 sparse fieldsets.
type WorkflowField string

// List of possible Workflow fields.
const (
	WorkflowFieldID      WorkflowField = "id"
	WorkflowFieldName    WorkflowField = "name"
	WorkflowFieldDefault WorkflowField = "defaultWorkflow"
)

// WorkflowStageField identifies a JSON-tagged attribute of WorkflowStage usable for v3 sparse fieldsets.
type WorkflowStageField string

// List of possible WorkflowStage fields.
const (
	WorkflowStageFieldID       WorkflowStageField = "id"
	WorkflowStageFieldName     WorkflowStageField = "name"
	WorkflowStageFieldWorkflow WorkflowStageField = "workflow"
)

// ActivityListFields selects sparse-fields slots for ActivityListResponse. Leave a slot empty to receive the
// API default for that entity; populate it to restrict the attributes returned.
type ActivityListFields struct {
	// Activities controls fields[activities]=… on the response.
	Activities []ActivityField
}

// apply writes every populated slot to query as a fields[entity]=… parameter.
func (f ActivityListFields) apply(query url.Values) {
	twapi.ApplySparseFields(query, "activities", f.Activities)
}

// AllocationGetFields selects sparse-fields slots for AllocationGetResponse. Leave a slot empty to receive the
// API default for that entity; populate it to restrict the attributes returned.
type AllocationGetFields struct {
	// Allocation controls fields[allocations]=… on the response.
	Allocation []AllocationField
}

// apply writes every populated slot to query as a fields[entity]=… parameter.
func (f AllocationGetFields) apply(query url.Values) {
	twapi.ApplySparseFields(query, "allocations", f.Allocation)
}

// AllocationListFields selects sparse-fields slots for AllocationListResponse. Leave a slot empty to receive the
// API default for that entity; populate it to restrict the attributes returned.
type AllocationListFields struct {
	// Allocations controls fields[allocations]=… on the response.
	Allocations []AllocationField
}

// apply writes every populated slot to query as a fields[entity]=… parameter.
func (f AllocationListFields) apply(query url.Values) {
	twapi.ApplySparseFields(query, "allocations", f.Allocations)
}

// CalendarEventListFields selects sparse-fields slots for CalendarEventListResponse. Leave a slot empty to receive the
// API default for that entity; populate it to restrict the attributes returned.
type CalendarEventListFields struct {
	// Events controls fields[calendarsEvents]=… on the response.
	Events []CalendarEventField
	// Users controls fields[users]=… on the response.
	Users []UserField
	// Projects controls fields[projects]=… on the response.
	Projects []ProjectField
	// Tasks controls fields[tasks]=… on the response.
	Tasks []TaskField
	// Tasklists controls fields[tasklists]=… on the response.
	Tasklists []TasklistField
	// Companies controls fields[companies]=… on the response.
	Companies []CompanyField
	// Timelogs controls fields[timelogs]=… on the response.
	Timelogs []TimelogField
}

// apply writes every populated slot to query as a fields[entity]=… parameter.
func (f CalendarEventListFields) apply(query url.Values) {
	twapi.ApplySparseFields(query, "calendarsEvents", f.Events)
	twapi.ApplySparseFields(query, "users", f.Users)
	twapi.ApplySparseFields(query, "projects", f.Projects)
	twapi.ApplySparseFields(query, "tasks", f.Tasks)
	twapi.ApplySparseFields(query, "tasklists", f.Tasklists)
	twapi.ApplySparseFields(query, "companies", f.Companies)
	twapi.ApplySparseFields(query, "timelogs", f.Timelogs)
}

// CalendarListFields selects sparse-fields slots for CalendarListResponse. Leave a slot empty to receive the
// API default for that entity; populate it to restrict the attributes returned.
type CalendarListFields struct {
	// Calendars controls fields[calendars]=… on the response.
	Calendars []CalendarField
}

// apply writes every populated slot to query as a fields[entity]=… parameter.
func (f CalendarListFields) apply(query url.Values) {
	twapi.ApplySparseFields(query, "calendars", f.Calendars)
}

// CommentGetFields selects sparse-fields slots for CommentGetResponse. Leave a slot empty to receive the
// API default for that entity; populate it to restrict the attributes returned.
type CommentGetFields struct {
	// Comment controls fields[comments]=… on the response.
	Comment []CommentField
}

// apply writes every populated slot to query as a fields[entity]=… parameter.
func (f CommentGetFields) apply(query url.Values) {
	twapi.ApplySparseFields(query, "comments", f.Comment)
}

// CommentListFields selects sparse-fields slots for CommentListResponse. Leave a slot empty to receive the
// API default for that entity; populate it to restrict the attributes returned.
type CommentListFields struct {
	// Comments controls fields[comments]=… on the response.
	Comments []CommentField
}

// apply writes every populated slot to query as a fields[entity]=… parameter.
func (f CommentListFields) apply(query url.Values) {
	twapi.ApplySparseFields(query, "comments", f.Comments)
}

// CompanyGetFields selects sparse-fields slots for CompanyGetResponse. Leave a slot empty to receive the
// API default for that entity; populate it to restrict the attributes returned.
type CompanyGetFields struct {
	// Company controls fields[companies]=… on the response.
	Company []CompanyField
	// CustomFields controls fields[customfields]=… on the response.
	CustomFields []CustomFieldField
	// CustomFieldValues controls fields[customfieldCompanies]=… on the response.
	CustomFieldValues []CustomFieldValueField
}

// apply writes every populated slot to query as a fields[entity]=… parameter.
func (f CompanyGetFields) apply(query url.Values) {
	twapi.ApplySparseFields(query, "companies", f.Company)
	twapi.ApplySparseFields(query, "customfields", f.CustomFields)
	twapi.ApplySparseFields(query, "customfieldCompanies", f.CustomFieldValues)
}

// CompanyListFields selects sparse-fields slots for CompanyListResponse. Leave a slot empty to receive the
// API default for that entity; populate it to restrict the attributes returned.
type CompanyListFields struct {
	// Companies controls fields[companies]=… on the response.
	Companies []CompanyField
	// CustomFields controls fields[customfields]=… on the response.
	CustomFields []CustomFieldField
	// CustomFieldValues controls fields[customfieldCompanies]=… on the response.
	CustomFieldValues []CustomFieldValueField
}

// apply writes every populated slot to query as a fields[entity]=… parameter.
func (f CompanyListFields) apply(query url.Values) {
	twapi.ApplySparseFields(query, "companies", f.Companies)
	twapi.ApplySparseFields(query, "customfields", f.CustomFields)
	twapi.ApplySparseFields(query, "customfieldCompanies", f.CustomFieldValues)
}

// CustomFieldListFields selects sparse-fields slots for CustomFieldListResponse. Leave a slot empty to receive the
// API default for that entity; populate it to restrict the attributes returned.
type CustomFieldListFields struct {
	// CustomFields controls fields[customfields]=… on the response.
	CustomFields []CustomFieldField
}

// apply writes every populated slot to query as a fields[entity]=… parameter.
func (f CustomFieldListFields) apply(query url.Values) {
	twapi.ApplySparseFields(query, "customfields", f.CustomFields)
}

// CustomFieldValueListFields selects sparse-fields slots for CustomFieldValueListResponse. Leave a slot empty to receive the
// API default for that entity; populate it to restrict the attributes returned.
type CustomFieldValueListFields struct {
	// CustomFieldValues controls fields[customfieldValues]=… on the response.
	CustomFieldValues []CustomFieldValueField
}

// apply writes every populated slot to query as a fields[entity]=… parameter.
func (f CustomFieldValueListFields) apply(query url.Values) {
	twapi.ApplySparseFields(query, "customfieldValues", f.CustomFieldValues)
}

// JobRoleGetFields selects sparse-fields slots for JobRoleGetResponse. Leave a slot empty to receive the
// API default for that entity; populate it to restrict the attributes returned.
type JobRoleGetFields struct {
	// JobRole controls fields[jobRoles]=… on the response.
	JobRole []JobRoleField
}

// apply writes every populated slot to query as a fields[entity]=… parameter.
func (f JobRoleGetFields) apply(query url.Values) {
	twapi.ApplySparseFields(query, "jobRoles", f.JobRole)
}

// JobRoleListFields selects sparse-fields slots for JobRoleListResponse. Leave a slot empty to receive the
// API default for that entity; populate it to restrict the attributes returned.
type JobRoleListFields struct {
	// JobRoles controls fields[jobRoles]=… on the response.
	JobRoles []JobRoleField
}

// apply writes every populated slot to query as a fields[entity]=… parameter.
func (f JobRoleListFields) apply(query url.Values) {
	twapi.ApplySparseFields(query, "jobRoles", f.JobRoles)
}

// LinkListFields selects sparse-fields slots for LinkListResponse. Leave a slot empty to receive the
// API default for that entity; populate it to restrict the attributes returned.
type LinkListFields struct {
	// Links controls fields[links]=… on the response.
	Links []LinkField
}

// apply writes every populated slot to query as a fields[entity]=… parameter.
func (f LinkListFields) apply(query url.Values) {
	twapi.ApplySparseFields(query, "links", f.Links)
}

// MessageGetFields selects sparse-fields slots for MessageGetResponse. Leave a slot empty to receive the
// API default for that entity; populate it to restrict the attributes returned.
type MessageGetFields struct {
	// Message controls fields[messages]=… on the response.
	Message []MessageField
}

// apply writes every populated slot to query as a fields[entity]=… parameter.
func (f MessageGetFields) apply(query url.Values) {
	twapi.ApplySparseFields(query, "messages", f.Message)
}

// MessageListFields selects sparse-fields slots for MessageListResponse. Leave a slot empty to receive the
// API default for that entity; populate it to restrict the attributes returned.
type MessageListFields struct {
	// Messages controls fields[messages]=… on the response.
	Messages []MessageField
}

// apply writes every populated slot to query as a fields[entity]=… parameter.
func (f MessageListFields) apply(query url.Values) {
	twapi.ApplySparseFields(query, "messages", f.Messages)
}

// MessageReplyGetFields selects sparse-fields slots for MessageReplyGetResponse. Leave a slot empty to receive the
// API default for that entity; populate it to restrict the attributes returned.
type MessageReplyGetFields struct {
	// MessageReply controls fields[messageReplies]=… on the response.
	MessageReply []MessageReplyField
}

// apply writes every populated slot to query as a fields[entity]=… parameter.
func (f MessageReplyGetFields) apply(query url.Values) {
	twapi.ApplySparseFields(query, "messageReplies", f.MessageReply)
}

// MessageReplyListFields selects sparse-fields slots for MessageReplyListResponse. Leave a slot empty to receive the
// API default for that entity; populate it to restrict the attributes returned.
type MessageReplyListFields struct {
	// MessageReplies controls fields[messageReplies]=… on the response.
	MessageReplies []MessageReplyField
}

// apply writes every populated slot to query as a fields[entity]=… parameter.
func (f MessageReplyListFields) apply(query url.Values) {
	twapi.ApplySparseFields(query, "messageReplies", f.MessageReplies)
}

// MilestoneGetFields selects sparse-fields slots for MilestoneGetResponse. Leave a slot empty to receive the
// API default for that entity; populate it to restrict the attributes returned.
type MilestoneGetFields struct {
	// Milestone controls fields[milestones]=… on the response.
	Milestone []MilestoneField
}

// apply writes every populated slot to query as a fields[entity]=… parameter.
func (f MilestoneGetFields) apply(query url.Values) {
	twapi.ApplySparseFields(query, "milestones", f.Milestone)
}

// MilestoneListFields selects sparse-fields slots for MilestoneListResponse. Leave a slot empty to receive the
// API default for that entity; populate it to restrict the attributes returned.
type MilestoneListFields struct {
	// Milestones controls fields[milestones]=… on the response.
	Milestones []MilestoneField
}

// apply writes every populated slot to query as a fields[entity]=… parameter.
func (f MilestoneListFields) apply(query url.Values) {
	twapi.ApplySparseFields(query, "milestones", f.Milestones)
}

// NotebookGetFields selects sparse-fields slots for NotebookGetResponse. Leave a slot empty to receive the
// API default for that entity; populate it to restrict the attributes returned.
type NotebookGetFields struct {
	// Notebook controls fields[notebooks]=… on the response.
	Notebook []NotebookField
}

// apply writes every populated slot to query as a fields[entity]=… parameter.
func (f NotebookGetFields) apply(query url.Values) {
	twapi.ApplySparseFields(query, "notebooks", f.Notebook)
}

// NotebookListFields selects sparse-fields slots for NotebookListResponse. Leave a slot empty to receive the
// API default for that entity; populate it to restrict the attributes returned.
type NotebookListFields struct {
	// Notebooks controls fields[notebooks]=… on the response.
	Notebooks []NotebookField
}

// apply writes every populated slot to query as a fields[entity]=… parameter.
func (f NotebookListFields) apply(query url.Values) {
	twapi.ApplySparseFields(query, "notebooks", f.Notebooks)
}

// ProjectBudgetListFields selects sparse-fields slots for ProjectBudgetListResponse. Leave a slot empty to receive the
// API default for that entity; populate it to restrict the attributes returned.
type ProjectBudgetListFields struct {
	// Budgets controls fields[projectBudgets]=… on the response.
	Budgets []ProjectBudgetField
}

// apply writes every populated slot to query as a fields[entity]=… parameter.
func (f ProjectBudgetListFields) apply(query url.Values) {
	twapi.ApplySparseFields(query, "projectBudgets", f.Budgets)
}

// ProjectCategoryGetFields selects sparse-fields slots for ProjectCategoryGetResponse. Leave a slot empty to receive the
// API default for that entity; populate it to restrict the attributes returned.
type ProjectCategoryGetFields struct {
	// ProjectCategory controls fields[projectCategories]=… on the response.
	ProjectCategory []ProjectCategoryField
}

// apply writes every populated slot to query as a fields[entity]=… parameter.
func (f ProjectCategoryGetFields) apply(query url.Values) {
	twapi.ApplySparseFields(query, "projectCategories", f.ProjectCategory)
}

// ProjectCategoryListFields selects sparse-fields slots for ProjectCategoryListResponse. Leave a slot empty to receive the
// API default for that entity; populate it to restrict the attributes returned.
type ProjectCategoryListFields struct {
	// ProjectCategories controls fields[projectCategories]=… on the response.
	ProjectCategories []ProjectCategoryField
}

// apply writes every populated slot to query as a fields[entity]=… parameter.
func (f ProjectCategoryListFields) apply(query url.Values) {
	twapi.ApplySparseFields(query, "projectCategories", f.ProjectCategories)
}

// ProjectGetFields selects sparse-fields slots for ProjectGetResponse. Leave a slot empty to receive the
// API default for that entity; populate it to restrict the attributes returned.
type ProjectGetFields struct {
	// Project controls fields[projects]=… on the response.
	Project []ProjectField
	// ProjectCategories controls fields[projectCategories]=… on the response.
	ProjectCategories []ProjectCategoryField
	// CustomFields controls fields[customfields]=… on the response.
	CustomFields []CustomFieldField
	// CustomFieldValues controls fields[customfieldProjects]=… on the response.
	CustomFieldValues []CustomFieldValueField
}

// apply writes every populated slot to query as a fields[entity]=… parameter.
func (f ProjectGetFields) apply(query url.Values) {
	twapi.ApplySparseFields(query, "projects", f.Project)
	twapi.ApplySparseFields(query, "projectCategories", f.ProjectCategories)
	twapi.ApplySparseFields(query, "customfields", f.CustomFields)
	twapi.ApplySparseFields(query, "customfieldProjects", f.CustomFieldValues)
}

// ProjectListFields selects sparse-fields slots for ProjectListResponse. Leave a slot empty to receive the
// API default for that entity; populate it to restrict the attributes returned.
type ProjectListFields struct {
	// Projects controls fields[projects]=… on the response.
	Projects []ProjectField
	// ProjectCategories controls fields[projectCategories]=… on the response.
	ProjectCategories []ProjectCategoryField
	// CustomFields controls fields[customfields]=… on the response.
	CustomFields []CustomFieldField
	// CustomFieldValues controls fields[customfieldProjects]=… on the response.
	CustomFieldValues []CustomFieldValueField
}

// apply writes every populated slot to query as a fields[entity]=… parameter.
func (f ProjectListFields) apply(query url.Values) {
	twapi.ApplySparseFields(query, "projects", f.Projects)
	twapi.ApplySparseFields(query, "projectCategories", f.ProjectCategories)
	twapi.ApplySparseFields(query, "customfields", f.CustomFields)
	twapi.ApplySparseFields(query, "customfieldProjects", f.CustomFieldValues)
}

// SearchFields selects sparse-fields slots for SearchResponse. Leave a slot empty to receive the
// API default for that entity; populate it to restrict the attributes returned.
type SearchFields struct {
	// Comments controls fields[comments]=… on the response.
	Comments []CommentSideloadField
	// Companies controls fields[companies]=… on the response.
	Companies []CompanyField
	// Links controls fields[links]=… on the response.
	Links []LinkField
	// Messages controls fields[messages]=… on the response.
	Messages []MessageField
	// Milestones controls fields[milestones]=… on the response.
	Milestones []MilestoneField
	// Notebooks controls fields[notebooks]=… on the response.
	Notebooks []NotebookField
	// Projects controls fields[projects]=… on the response.
	Projects []ProjectField
	// Tasklists controls fields[tasklists]=… on the response.
	Tasklists []TasklistField
	// Tasks controls fields[tasks]=… on the response.
	Tasks []TaskField
	// Teams controls fields[teams]=… on the response.
	Teams []TeamField
	// Timelogs controls fields[timelogs]=… on the response.
	Timelogs []TimelogField
	// Users controls fields[users]=… on the response.
	Users []UserField
}

// apply writes every populated slot to query as a fields[entity]=… parameter.
func (f SearchFields) apply(query url.Values) {
	twapi.ApplySparseFields(query, "comments", f.Comments)
	twapi.ApplySparseFields(query, "companies", f.Companies)
	twapi.ApplySparseFields(query, "links", f.Links)
	twapi.ApplySparseFields(query, "messages", f.Messages)
	twapi.ApplySparseFields(query, "milestones", f.Milestones)
	twapi.ApplySparseFields(query, "notebooks", f.Notebooks)
	twapi.ApplySparseFields(query, "projects", f.Projects)
	twapi.ApplySparseFields(query, "tasklists", f.Tasklists)
	twapi.ApplySparseFields(query, "tasks", f.Tasks)
	twapi.ApplySparseFields(query, "teams", f.Teams)
	twapi.ApplySparseFields(query, "timelogs", f.Timelogs)
	twapi.ApplySparseFields(query, "users", f.Users)
}

// SkillListFields selects sparse-fields slots for SkillListResponse. Leave a slot empty to receive the
// API default for that entity; populate it to restrict the attributes returned.
type SkillListFields struct {
	// Skills controls fields[skill]=… on the response.
	Skills []SkillField
}

// apply writes every populated slot to query as a fields[entity]=… parameter.
func (f SkillListFields) apply(query url.Values) {
	twapi.ApplySparseFields(query, "skill", f.Skills)
}

// TagListFields selects sparse-fields slots for TagListResponse. Leave a slot empty to receive the
// API default for that entity; populate it to restrict the attributes returned.
type TagListFields struct {
	// Tags controls fields[tags]=… on the response.
	Tags []TagField
}

// apply writes every populated slot to query as a fields[entity]=… parameter.
func (f TagListFields) apply(query url.Values) {
	twapi.ApplySparseFields(query, "tags", f.Tags)
}

// TaskGetFields selects sparse-fields slots for TaskGetResponse. Leave a slot empty to receive the
// API default for that entity; populate it to restrict the attributes returned.
type TaskGetFields struct {
	// Task controls fields[tasks]=… on the response.
	Task []TaskField
	// CustomFields controls fields[customfields]=… on the response.
	CustomFields []CustomFieldField
	// CustomFieldValues controls fields[customfieldTasks]=… on the response.
	CustomFieldValues []CustomFieldValueField
}

// apply writes every populated slot to query as a fields[entity]=… parameter.
func (f TaskGetFields) apply(query url.Values) {
	twapi.ApplySparseFields(query, "tasks", f.Task)
	twapi.ApplySparseFields(query, "customfields", f.CustomFields)
	twapi.ApplySparseFields(query, "customfieldTasks", f.CustomFieldValues)
}

// TaskListFields selects sparse-fields slots for TaskListResponse. Leave a slot empty to receive the
// API default for that entity; populate it to restrict the attributes returned.
type TaskListFields struct {
	// Tasks controls fields[tasks]=… on the response.
	Tasks []TaskField
	// CustomFields controls fields[customfields]=… on the response.
	CustomFields []CustomFieldField
	// CustomFieldValues controls fields[customfieldTasks]=… on the response.
	CustomFieldValues []CustomFieldValueField
}

// apply writes every populated slot to query as a fields[entity]=… parameter.
func (f TaskListFields) apply(query url.Values) {
	twapi.ApplySparseFields(query, "tasks", f.Tasks)
	twapi.ApplySparseFields(query, "customfields", f.CustomFields)
	twapi.ApplySparseFields(query, "customfieldTasks", f.CustomFieldValues)
}

// TasklistBudgetListFields selects sparse-fields slots for TasklistBudgetListResponse. Leave a slot empty to receive the
// API default for that entity; populate it to restrict the attributes returned.
type TasklistBudgetListFields struct {
	// TasklistBudgets controls fields[tasklistBudgets]=… on the response.
	TasklistBudgets []TasklistBudgetField
	// Notifications controls fields[notifications]=… on the response.
	Notifications []TasklistBudgetNotificationField
	// ProjectBudgets controls fields[projectBudgets]=… on the response.
	ProjectBudgets []ProjectBudgetField
	// Tasklists controls fields[tasklists]=… on the response.
	Tasklists []TasklistField
}

// apply writes every populated slot to query as a fields[entity]=… parameter.
func (f TasklistBudgetListFields) apply(query url.Values) {
	twapi.ApplySparseFields(query, "tasklistBudgets", f.TasklistBudgets)
	twapi.ApplySparseFields(query, "notifications", f.Notifications)
	twapi.ApplySparseFields(query, "projectBudgets", f.ProjectBudgets)
	twapi.ApplySparseFields(query, "tasklists", f.Tasklists)
}

// TasklistGetFields selects sparse-fields slots for TasklistGetResponse. Leave a slot empty to receive the
// API default for that entity; populate it to restrict the attributes returned.
type TasklistGetFields struct {
	// Tasklist controls fields[tasklists]=… on the response.
	Tasklist []TasklistField
}

// apply writes every populated slot to query as a fields[entity]=… parameter.
func (f TasklistGetFields) apply(query url.Values) {
	twapi.ApplySparseFields(query, "tasklists", f.Tasklist)
}

// TasklistListFields selects sparse-fields slots for TasklistListResponse. Leave a slot empty to receive the
// API default for that entity; populate it to restrict the attributes returned.
type TasklistListFields struct {
	// Tasklists controls fields[tasklists]=… on the response.
	Tasklists []TasklistField
}

// apply writes every populated slot to query as a fields[entity]=… parameter.
func (f TasklistListFields) apply(query url.Values) {
	twapi.ApplySparseFields(query, "tasklists", f.Tasklists)
}

// TeamListFields selects sparse-fields slots for TeamListResponse. Leave a slot empty to receive the
// API default for that entity; populate it to restrict the attributes returned.
type TeamListFields struct {
	// Teams controls fields[teams]=… on the response.
	Teams []TeamField
}

// apply writes every populated slot to query as a fields[entity]=… parameter.
func (f TeamListFields) apply(query url.Values) {
	twapi.ApplySparseFields(query, "teams", f.Teams)
}

// TimeReportListFields selects sparse-fields slots for TimeReportListResponse. Leave a slot empty to receive the
// API default for that entity; populate it to restrict the attributes returned.
type TimeReportListFields struct {
	// Users controls fields[users]=… on the response.
	Users []UserField
	// Projects controls fields[projects]=… on the response.
	Projects []ProjectField
}

// apply writes every populated slot to query as a fields[entity]=… parameter.
func (f TimeReportListFields) apply(query url.Values) {
	twapi.ApplySparseFields(query, "users", f.Users)
	twapi.ApplySparseFields(query, "projects", f.Projects)
}

// TimelogGetFields selects sparse-fields slots for TimelogGetResponse. Leave a slot empty to receive the
// API default for that entity; populate it to restrict the attributes returned.
type TimelogGetFields struct {
	// Timelog controls fields[timelogs]=… on the response.
	Timelog []TimelogField
}

// apply writes every populated slot to query as a fields[entity]=… parameter.
func (f TimelogGetFields) apply(query url.Values) {
	twapi.ApplySparseFields(query, "timelogs", f.Timelog)
}

// TimelogListFields selects sparse-fields slots for TimelogListResponse. Leave a slot empty to receive the
// API default for that entity; populate it to restrict the attributes returned.
type TimelogListFields struct {
	// Timelogs controls fields[timelogs]=… on the response.
	Timelogs []TimelogField
}

// apply writes every populated slot to query as a fields[entity]=… parameter.
func (f TimelogListFields) apply(query url.Values) {
	twapi.ApplySparseFields(query, "timelogs", f.Timelogs)
}

// TimerGetFields selects sparse-fields slots for TimerGetResponse. Leave a slot empty to receive the
// API default for that entity; populate it to restrict the attributes returned.
type TimerGetFields struct {
	// Timer controls fields[timers]=… on the response.
	Timer []TimerField
}

// apply writes every populated slot to query as a fields[entity]=… parameter.
func (f TimerGetFields) apply(query url.Values) {
	twapi.ApplySparseFields(query, "timers", f.Timer)
}

// TimerListFields selects sparse-fields slots for TimerListResponse. Leave a slot empty to receive the
// API default for that entity; populate it to restrict the attributes returned.
type TimerListFields struct {
	// Timers controls fields[timers]=… on the response.
	Timers []TimerField
}

// apply writes every populated slot to query as a fields[entity]=… parameter.
func (f TimerListFields) apply(query url.Values) {
	twapi.ApplySparseFields(query, "timers", f.Timers)
}

// UserGetFields selects sparse-fields slots for UserGetResponse. Leave a slot empty to receive the
// API default for that entity; populate it to restrict the attributes returned.
type UserGetFields struct {
	// User controls fields[person]=… on the response.
	User []UserField
}

// apply writes every populated slot to query as a fields[entity]=… parameter.
func (f UserGetFields) apply(query url.Values) {
	twapi.ApplySparseFields(query, "person", f.User)
}

// UserListFields selects sparse-fields slots for UserListResponse. Leave a slot empty to receive the
// API default for that entity; populate it to restrict the attributes returned.
type UserListFields struct {
	// Users controls fields[people]=… on the response.
	Users []UserField
}

// apply writes every populated slot to query as a fields[entity]=… parameter.
func (f UserListFields) apply(query url.Values) {
	twapi.ApplySparseFields(query, "people", f.Users)
}

// WorkflowGetFields selects sparse-fields slots for WorkflowGetResponse. Leave a slot empty to receive the
// API default for that entity; populate it to restrict the attributes returned.
type WorkflowGetFields struct {
	// Workflow controls fields[workflows]=… on the response.
	Workflow []WorkflowField
}

// apply writes every populated slot to query as a fields[entity]=… parameter.
func (f WorkflowGetFields) apply(query url.Values) {
	twapi.ApplySparseFields(query, "workflows", f.Workflow)
}

// WorkflowListFields selects sparse-fields slots for WorkflowListResponse. Leave a slot empty to receive the
// API default for that entity; populate it to restrict the attributes returned.
type WorkflowListFields struct {
	// Workflows controls fields[workflows]=… on the response.
	Workflows []WorkflowField
}

// apply writes every populated slot to query as a fields[entity]=… parameter.
func (f WorkflowListFields) apply(query url.Values) {
	twapi.ApplySparseFields(query, "workflows", f.Workflows)
}

// WorkflowStageGetFields selects sparse-fields slots for WorkflowStageGetResponse. Leave a slot empty to receive the
// API default for that entity; populate it to restrict the attributes returned.
type WorkflowStageGetFields struct {
	// Stage controls fields[stages]=… on the response.
	Stage []WorkflowStageField
}

// apply writes every populated slot to query as a fields[entity]=… parameter.
func (f WorkflowStageGetFields) apply(query url.Values) {
	twapi.ApplySparseFields(query, "stages", f.Stage)
}

// WorkflowStageListFields selects sparse-fields slots for WorkflowStageListResponse. Leave a slot empty to receive the
// API default for that entity; populate it to restrict the attributes returned.
type WorkflowStageListFields struct {
	// Stages controls fields[stages]=… on the response.
	Stages []WorkflowStageField
}

// apply writes every populated slot to query as a fields[entity]=… parameter.
func (f WorkflowStageListFields) apply(query url.Values) {
	twapi.ApplySparseFields(query, "stages", f.Stages)
}
