// Code generated by sparsefieldsgen; DO NOT EDIT.

package projects

import (
	"net/url"
	"strings"
	"testing"
)

// TestActivityListFieldsApply verifies that populated ActivityListFields slots emit the
// expected fields[entity]=… query parameters.
func TestActivityListFieldsApply(t *testing.T) {
	fields := ActivityListFields{
		Activities: []ActivityField{ActivityFieldID},
	}
	query := url.Values{}
	fields.apply(query)
	checks := map[string]string{
		"fields[activities]": "id",
	}
	for key, want := range checks {
		if got := query.Get(key); got != want {
			t.Errorf("%s = %q, want %q", key, got, want)
		}
	}
}

// TestActivityListFieldsZeroValue verifies that an unset ActivityListFields emits no
// fields[*]=… query parameters.
func TestActivityListFieldsZeroValue(t *testing.T) {
	var fields ActivityListFields
	query := url.Values{}
	fields.apply(query)
	for key := range query {
		if strings.HasPrefix(key, "fields[") {
			t.Errorf("unexpected sparse-fields parameter %q on zero-value container", key)
		}
	}
}

// TestCalendarEventListFieldsApply verifies that populated CalendarEventListFields slots emit the
// expected fields[entity]=… query parameters.
func TestCalendarEventListFieldsApply(t *testing.T) {
	fields := CalendarEventListFields{
		Events:    []CalendarEventField{CalendarEventFieldID},
		Users:     []UserField{UserFieldID},
		Projects:  []ProjectField{ProjectFieldID},
		Tasks:     []TaskField{TaskFieldID},
		Tasklists: []TasklistField{TasklistFieldID},
		Companies: []CompanyField{CompanyFieldID},
		Timelogs:  []TimelogField{TimelogFieldID},
	}
	query := url.Values{}
	fields.apply(query)
	checks := map[string]string{
		"fields[events]":    "id",
		"fields[users]":     "id",
		"fields[projects]":  "id",
		"fields[tasks]":     "id",
		"fields[tasklists]": "id",
		"fields[companies]": "id",
		"fields[timelogs]":  "id",
	}
	for key, want := range checks {
		if got := query.Get(key); got != want {
			t.Errorf("%s = %q, want %q", key, got, want)
		}
	}
}

// TestCalendarEventListFieldsZeroValue verifies that an unset CalendarEventListFields emits no
// fields[*]=… query parameters.
func TestCalendarEventListFieldsZeroValue(t *testing.T) {
	var fields CalendarEventListFields
	query := url.Values{}
	fields.apply(query)
	for key := range query {
		if strings.HasPrefix(key, "fields[") {
			t.Errorf("unexpected sparse-fields parameter %q on zero-value container", key)
		}
	}
}

// TestCalendarListFieldsApply verifies that populated CalendarListFields slots emit the
// expected fields[entity]=… query parameters.
func TestCalendarListFieldsApply(t *testing.T) {
	fields := CalendarListFields{
		Calendars: []CalendarField{CalendarFieldID},
	}
	query := url.Values{}
	fields.apply(query)
	checks := map[string]string{
		"fields[calendars]": "id",
	}
	for key, want := range checks {
		if got := query.Get(key); got != want {
			t.Errorf("%s = %q, want %q", key, got, want)
		}
	}
}

// TestCalendarListFieldsZeroValue verifies that an unset CalendarListFields emits no
// fields[*]=… query parameters.
func TestCalendarListFieldsZeroValue(t *testing.T) {
	var fields CalendarListFields
	query := url.Values{}
	fields.apply(query)
	for key := range query {
		if strings.HasPrefix(key, "fields[") {
			t.Errorf("unexpected sparse-fields parameter %q on zero-value container", key)
		}
	}
}

// TestCommentListFieldsApply verifies that populated CommentListFields slots emit the
// expected fields[entity]=… query parameters.
func TestCommentListFieldsApply(t *testing.T) {
	fields := CommentListFields{
		Comments: []CommentField{CommentFieldID},
	}
	query := url.Values{}
	fields.apply(query)
	checks := map[string]string{
		"fields[comments]": "id",
	}
	for key, want := range checks {
		if got := query.Get(key); got != want {
			t.Errorf("%s = %q, want %q", key, got, want)
		}
	}
}

// TestCommentListFieldsZeroValue verifies that an unset CommentListFields emits no
// fields[*]=… query parameters.
func TestCommentListFieldsZeroValue(t *testing.T) {
	var fields CommentListFields
	query := url.Values{}
	fields.apply(query)
	for key := range query {
		if strings.HasPrefix(key, "fields[") {
			t.Errorf("unexpected sparse-fields parameter %q on zero-value container", key)
		}
	}
}

// TestCompanyListFieldsApply verifies that populated CompanyListFields slots emit the
// expected fields[entity]=… query parameters.
func TestCompanyListFieldsApply(t *testing.T) {
	fields := CompanyListFields{
		Companies:         []CompanyField{CompanyFieldID},
		CustomFields:      []CustomFieldField{CustomFieldFieldOptions},
		CustomFieldValues: []CustomFieldValueField{CustomFieldValueFieldID},
	}
	query := url.Values{}
	fields.apply(query)
	checks := map[string]string{
		"fields[companies]":            "id",
		"fields[customfields]":         "options",
		"fields[customfieldCompanies]": "id",
	}
	for key, want := range checks {
		if got := query.Get(key); got != want {
			t.Errorf("%s = %q, want %q", key, got, want)
		}
	}
}

// TestCompanyListFieldsZeroValue verifies that an unset CompanyListFields emits no
// fields[*]=… query parameters.
func TestCompanyListFieldsZeroValue(t *testing.T) {
	var fields CompanyListFields
	query := url.Values{}
	fields.apply(query)
	for key := range query {
		if strings.HasPrefix(key, "fields[") {
			t.Errorf("unexpected sparse-fields parameter %q on zero-value container", key)
		}
	}
}

// TestCustomFieldListFieldsApply verifies that populated CustomFieldListFields slots emit the
// expected fields[entity]=… query parameters.
func TestCustomFieldListFieldsApply(t *testing.T) {
	fields := CustomFieldListFields{
		CustomFields: []CustomFieldField{CustomFieldFieldOptions},
	}
	query := url.Values{}
	fields.apply(query)
	checks := map[string]string{
		"fields[customfields]": "options",
	}
	for key, want := range checks {
		if got := query.Get(key); got != want {
			t.Errorf("%s = %q, want %q", key, got, want)
		}
	}
}

// TestCustomFieldListFieldsZeroValue verifies that an unset CustomFieldListFields emits no
// fields[*]=… query parameters.
func TestCustomFieldListFieldsZeroValue(t *testing.T) {
	var fields CustomFieldListFields
	query := url.Values{}
	fields.apply(query)
	for key := range query {
		if strings.HasPrefix(key, "fields[") {
			t.Errorf("unexpected sparse-fields parameter %q on zero-value container", key)
		}
	}
}

// TestCustomFieldValueListFieldsApply verifies that populated CustomFieldValueListFields slots emit the
// expected fields[entity]=… query parameters.
func TestCustomFieldValueListFieldsApply(t *testing.T) {
	fields := CustomFieldValueListFields{
		CustomFieldValues: []CustomFieldValueField{CustomFieldValueFieldID},
	}
	query := url.Values{}
	fields.apply(query)
	checks := map[string]string{
		"fields[customfieldValues]": "id",
	}
	for key, want := range checks {
		if got := query.Get(key); got != want {
			t.Errorf("%s = %q, want %q", key, got, want)
		}
	}
}

// TestCustomFieldValueListFieldsZeroValue verifies that an unset CustomFieldValueListFields emits no
// fields[*]=… query parameters.
func TestCustomFieldValueListFieldsZeroValue(t *testing.T) {
	var fields CustomFieldValueListFields
	query := url.Values{}
	fields.apply(query)
	for key := range query {
		if strings.HasPrefix(key, "fields[") {
			t.Errorf("unexpected sparse-fields parameter %q on zero-value container", key)
		}
	}
}

// TestJobRoleListFieldsApply verifies that populated JobRoleListFields slots emit the
// expected fields[entity]=… query parameters.
func TestJobRoleListFieldsApply(t *testing.T) {
	fields := JobRoleListFields{
		JobRoles: []JobRoleField{JobRoleFieldID},
	}
	query := url.Values{}
	fields.apply(query)
	checks := map[string]string{
		"fields[jobRoles]": "id",
	}
	for key, want := range checks {
		if got := query.Get(key); got != want {
			t.Errorf("%s = %q, want %q", key, got, want)
		}
	}
}

// TestJobRoleListFieldsZeroValue verifies that an unset JobRoleListFields emits no
// fields[*]=… query parameters.
func TestJobRoleListFieldsZeroValue(t *testing.T) {
	var fields JobRoleListFields
	query := url.Values{}
	fields.apply(query)
	for key := range query {
		if strings.HasPrefix(key, "fields[") {
			t.Errorf("unexpected sparse-fields parameter %q on zero-value container", key)
		}
	}
}

// TestLinkListFieldsApply verifies that populated LinkListFields slots emit the
// expected fields[entity]=… query parameters.
func TestLinkListFieldsApply(t *testing.T) {
	fields := LinkListFields{
		Links: []LinkField{LinkFieldID},
	}
	query := url.Values{}
	fields.apply(query)
	checks := map[string]string{
		"fields[links]": "id",
	}
	for key, want := range checks {
		if got := query.Get(key); got != want {
			t.Errorf("%s = %q, want %q", key, got, want)
		}
	}
}

// TestLinkListFieldsZeroValue verifies that an unset LinkListFields emits no
// fields[*]=… query parameters.
func TestLinkListFieldsZeroValue(t *testing.T) {
	var fields LinkListFields
	query := url.Values{}
	fields.apply(query)
	for key := range query {
		if strings.HasPrefix(key, "fields[") {
			t.Errorf("unexpected sparse-fields parameter %q on zero-value container", key)
		}
	}
}

// TestMessageListFieldsApply verifies that populated MessageListFields slots emit the
// expected fields[entity]=… query parameters.
func TestMessageListFieldsApply(t *testing.T) {
	fields := MessageListFields{
		Messages: []MessageField{MessageFieldID},
	}
	query := url.Values{}
	fields.apply(query)
	checks := map[string]string{
		"fields[messages]": "id",
	}
	for key, want := range checks {
		if got := query.Get(key); got != want {
			t.Errorf("%s = %q, want %q", key, got, want)
		}
	}
}

// TestMessageListFieldsZeroValue verifies that an unset MessageListFields emits no
// fields[*]=… query parameters.
func TestMessageListFieldsZeroValue(t *testing.T) {
	var fields MessageListFields
	query := url.Values{}
	fields.apply(query)
	for key := range query {
		if strings.HasPrefix(key, "fields[") {
			t.Errorf("unexpected sparse-fields parameter %q on zero-value container", key)
		}
	}
}

// TestMessageReplyListFieldsApply verifies that populated MessageReplyListFields slots emit the
// expected fields[entity]=… query parameters.
func TestMessageReplyListFieldsApply(t *testing.T) {
	fields := MessageReplyListFields{
		MessageReplies: []MessageReplyField{MessageReplyFieldID},
	}
	query := url.Values{}
	fields.apply(query)
	checks := map[string]string{
		"fields[messageReplies]": "id",
	}
	for key, want := range checks {
		if got := query.Get(key); got != want {
			t.Errorf("%s = %q, want %q", key, got, want)
		}
	}
}

// TestMessageReplyListFieldsZeroValue verifies that an unset MessageReplyListFields emits no
// fields[*]=… query parameters.
func TestMessageReplyListFieldsZeroValue(t *testing.T) {
	var fields MessageReplyListFields
	query := url.Values{}
	fields.apply(query)
	for key := range query {
		if strings.HasPrefix(key, "fields[") {
			t.Errorf("unexpected sparse-fields parameter %q on zero-value container", key)
		}
	}
}

// TestMilestoneListFieldsApply verifies that populated MilestoneListFields slots emit the
// expected fields[entity]=… query parameters.
func TestMilestoneListFieldsApply(t *testing.T) {
	fields := MilestoneListFields{
		Milestones: []MilestoneField{MilestoneFieldID},
	}
	query := url.Values{}
	fields.apply(query)
	checks := map[string]string{
		"fields[milestones]": "id",
	}
	for key, want := range checks {
		if got := query.Get(key); got != want {
			t.Errorf("%s = %q, want %q", key, got, want)
		}
	}
}

// TestMilestoneListFieldsZeroValue verifies that an unset MilestoneListFields emits no
// fields[*]=… query parameters.
func TestMilestoneListFieldsZeroValue(t *testing.T) {
	var fields MilestoneListFields
	query := url.Values{}
	fields.apply(query)
	for key := range query {
		if strings.HasPrefix(key, "fields[") {
			t.Errorf("unexpected sparse-fields parameter %q on zero-value container", key)
		}
	}
}

// TestNotebookListFieldsApply verifies that populated NotebookListFields slots emit the
// expected fields[entity]=… query parameters.
func TestNotebookListFieldsApply(t *testing.T) {
	fields := NotebookListFields{
		Notebooks: []NotebookField{NotebookFieldID},
	}
	query := url.Values{}
	fields.apply(query)
	checks := map[string]string{
		"fields[notebooks]": "id",
	}
	for key, want := range checks {
		if got := query.Get(key); got != want {
			t.Errorf("%s = %q, want %q", key, got, want)
		}
	}
}

// TestNotebookListFieldsZeroValue verifies that an unset NotebookListFields emits no
// fields[*]=… query parameters.
func TestNotebookListFieldsZeroValue(t *testing.T) {
	var fields NotebookListFields
	query := url.Values{}
	fields.apply(query)
	for key := range query {
		if strings.HasPrefix(key, "fields[") {
			t.Errorf("unexpected sparse-fields parameter %q on zero-value container", key)
		}
	}
}

// TestProjectBudgetListFieldsApply verifies that populated ProjectBudgetListFields slots emit the
// expected fields[entity]=… query parameters.
func TestProjectBudgetListFieldsApply(t *testing.T) {
	fields := ProjectBudgetListFields{
		Budgets: []ProjectBudgetField{ProjectBudgetFieldID},
	}
	query := url.Values{}
	fields.apply(query)
	checks := map[string]string{
		"fields[budgets]": "id",
	}
	for key, want := range checks {
		if got := query.Get(key); got != want {
			t.Errorf("%s = %q, want %q", key, got, want)
		}
	}
}

// TestProjectBudgetListFieldsZeroValue verifies that an unset ProjectBudgetListFields emits no
// fields[*]=… query parameters.
func TestProjectBudgetListFieldsZeroValue(t *testing.T) {
	var fields ProjectBudgetListFields
	query := url.Values{}
	fields.apply(query)
	for key := range query {
		if strings.HasPrefix(key, "fields[") {
			t.Errorf("unexpected sparse-fields parameter %q on zero-value container", key)
		}
	}
}

// TestProjectCategoryListFieldsApply verifies that populated ProjectCategoryListFields slots emit the
// expected fields[entity]=… query parameters.
func TestProjectCategoryListFieldsApply(t *testing.T) {
	fields := ProjectCategoryListFields{
		ProjectCategories: []ProjectCategoryField{ProjectCategoryFieldID},
	}
	query := url.Values{}
	fields.apply(query)
	checks := map[string]string{
		"fields[projectCategories]": "id",
	}
	for key, want := range checks {
		if got := query.Get(key); got != want {
			t.Errorf("%s = %q, want %q", key, got, want)
		}
	}
}

// TestProjectCategoryListFieldsZeroValue verifies that an unset ProjectCategoryListFields emits no
// fields[*]=… query parameters.
func TestProjectCategoryListFieldsZeroValue(t *testing.T) {
	var fields ProjectCategoryListFields
	query := url.Values{}
	fields.apply(query)
	for key := range query {
		if strings.HasPrefix(key, "fields[") {
			t.Errorf("unexpected sparse-fields parameter %q on zero-value container", key)
		}
	}
}

// TestProjectListFieldsApply verifies that populated ProjectListFields slots emit the
// expected fields[entity]=… query parameters.
func TestProjectListFieldsApply(t *testing.T) {
	fields := ProjectListFields{
		Projects:          []ProjectField{ProjectFieldID},
		ProjectCategories: []ProjectCategoryField{ProjectCategoryFieldID},
		CustomFields:      []CustomFieldField{CustomFieldFieldOptions},
		CustomFieldValues: []CustomFieldValueField{CustomFieldValueFieldID},
	}
	query := url.Values{}
	fields.apply(query)
	checks := map[string]string{
		"fields[projects]":            "id",
		"fields[projectCategories]":   "id",
		"fields[customfields]":        "options",
		"fields[customfieldProjects]": "id",
	}
	for key, want := range checks {
		if got := query.Get(key); got != want {
			t.Errorf("%s = %q, want %q", key, got, want)
		}
	}
}

// TestProjectListFieldsZeroValue verifies that an unset ProjectListFields emits no
// fields[*]=… query parameters.
func TestProjectListFieldsZeroValue(t *testing.T) {
	var fields ProjectListFields
	query := url.Values{}
	fields.apply(query)
	for key := range query {
		if strings.HasPrefix(key, "fields[") {
			t.Errorf("unexpected sparse-fields parameter %q on zero-value container", key)
		}
	}
}

// TestSkillListFieldsApply verifies that populated SkillListFields slots emit the
// expected fields[entity]=… query parameters.
func TestSkillListFieldsApply(t *testing.T) {
	fields := SkillListFields{
		Skills: []SkillField{SkillFieldID},
	}
	query := url.Values{}
	fields.apply(query)
	checks := map[string]string{
		"fields[skills]": "id",
	}
	for key, want := range checks {
		if got := query.Get(key); got != want {
			t.Errorf("%s = %q, want %q", key, got, want)
		}
	}
}

// TestSkillListFieldsZeroValue verifies that an unset SkillListFields emits no
// fields[*]=… query parameters.
func TestSkillListFieldsZeroValue(t *testing.T) {
	var fields SkillListFields
	query := url.Values{}
	fields.apply(query)
	for key := range query {
		if strings.HasPrefix(key, "fields[") {
			t.Errorf("unexpected sparse-fields parameter %q on zero-value container", key)
		}
	}
}

// TestTagListFieldsApply verifies that populated TagListFields slots emit the
// expected fields[entity]=… query parameters.
func TestTagListFieldsApply(t *testing.T) {
	fields := TagListFields{
		Tags: []TagField{TagFieldID},
	}
	query := url.Values{}
	fields.apply(query)
	checks := map[string]string{
		"fields[tags]": "id",
	}
	for key, want := range checks {
		if got := query.Get(key); got != want {
			t.Errorf("%s = %q, want %q", key, got, want)
		}
	}
}

// TestTagListFieldsZeroValue verifies that an unset TagListFields emits no
// fields[*]=… query parameters.
func TestTagListFieldsZeroValue(t *testing.T) {
	var fields TagListFields
	query := url.Values{}
	fields.apply(query)
	for key := range query {
		if strings.HasPrefix(key, "fields[") {
			t.Errorf("unexpected sparse-fields parameter %q on zero-value container", key)
		}
	}
}

// TestTaskListFieldsApply verifies that populated TaskListFields slots emit the
// expected fields[entity]=… query parameters.
func TestTaskListFieldsApply(t *testing.T) {
	fields := TaskListFields{
		Tasks:             []TaskField{TaskFieldID},
		CustomFields:      []CustomFieldField{CustomFieldFieldOptions},
		CustomFieldValues: []CustomFieldValueField{CustomFieldValueFieldID},
	}
	query := url.Values{}
	fields.apply(query)
	checks := map[string]string{
		"fields[tasks]":            "id",
		"fields[customfields]":     "options",
		"fields[customfieldTasks]": "id",
	}
	for key, want := range checks {
		if got := query.Get(key); got != want {
			t.Errorf("%s = %q, want %q", key, got, want)
		}
	}
}

// TestTaskListFieldsZeroValue verifies that an unset TaskListFields emits no
// fields[*]=… query parameters.
func TestTaskListFieldsZeroValue(t *testing.T) {
	var fields TaskListFields
	query := url.Values{}
	fields.apply(query)
	for key := range query {
		if strings.HasPrefix(key, "fields[") {
			t.Errorf("unexpected sparse-fields parameter %q on zero-value container", key)
		}
	}
}

// TestTasklistBudgetListFieldsApply verifies that populated TasklistBudgetListFields slots emit the
// expected fields[entity]=… query parameters.
func TestTasklistBudgetListFieldsApply(t *testing.T) {
	fields := TasklistBudgetListFields{
		TasklistBudgets: []TasklistBudgetField{TasklistBudgetFieldID},
		Notifications:   []TasklistBudgetNotificationField{TasklistBudgetNotificationFieldID},
		ProjectBudgets:  []ProjectBudgetField{ProjectBudgetFieldID},
		Tasklists:       []TasklistField{TasklistFieldID},
	}
	query := url.Values{}
	fields.apply(query)
	checks := map[string]string{
		"fields[tasklistBudgets]": "id",
		"fields[notifications]":   "id",
		"fields[projectBudgets]":  "id",
		"fields[tasklists]":       "id",
	}
	for key, want := range checks {
		if got := query.Get(key); got != want {
			t.Errorf("%s = %q, want %q", key, got, want)
		}
	}
}

// TestTasklistBudgetListFieldsZeroValue verifies that an unset TasklistBudgetListFields emits no
// fields[*]=… query parameters.
func TestTasklistBudgetListFieldsZeroValue(t *testing.T) {
	var fields TasklistBudgetListFields
	query := url.Values{}
	fields.apply(query)
	for key := range query {
		if strings.HasPrefix(key, "fields[") {
			t.Errorf("unexpected sparse-fields parameter %q on zero-value container", key)
		}
	}
}

// TestTasklistListFieldsApply verifies that populated TasklistListFields slots emit the
// expected fields[entity]=… query parameters.
func TestTasklistListFieldsApply(t *testing.T) {
	fields := TasklistListFields{
		Tasklists: []TasklistField{TasklistFieldID},
	}
	query := url.Values{}
	fields.apply(query)
	checks := map[string]string{
		"fields[tasklists]": "id",
	}
	for key, want := range checks {
		if got := query.Get(key); got != want {
			t.Errorf("%s = %q, want %q", key, got, want)
		}
	}
}

// TestTasklistListFieldsZeroValue verifies that an unset TasklistListFields emits no
// fields[*]=… query parameters.
func TestTasklistListFieldsZeroValue(t *testing.T) {
	var fields TasklistListFields
	query := url.Values{}
	fields.apply(query)
	for key := range query {
		if strings.HasPrefix(key, "fields[") {
			t.Errorf("unexpected sparse-fields parameter %q on zero-value container", key)
		}
	}
}

// TestTeamListFieldsApply verifies that populated TeamListFields slots emit the
// expected fields[entity]=… query parameters.
func TestTeamListFieldsApply(t *testing.T) {
	fields := TeamListFields{
		Teams: []TeamField{TeamFieldID},
	}
	query := url.Values{}
	fields.apply(query)
	checks := map[string]string{
		"fields[teams]": "id",
	}
	for key, want := range checks {
		if got := query.Get(key); got != want {
			t.Errorf("%s = %q, want %q", key, got, want)
		}
	}
}

// TestTeamListFieldsZeroValue verifies that an unset TeamListFields emits no
// fields[*]=… query parameters.
func TestTeamListFieldsZeroValue(t *testing.T) {
	var fields TeamListFields
	query := url.Values{}
	fields.apply(query)
	for key := range query {
		if strings.HasPrefix(key, "fields[") {
			t.Errorf("unexpected sparse-fields parameter %q on zero-value container", key)
		}
	}
}

// TestTimeReportListFieldsApply verifies that populated TimeReportListFields slots emit the
// expected fields[entity]=… query parameters.
func TestTimeReportListFieldsApply(t *testing.T) {
	fields := TimeReportListFields{
		Users:    []UserField{UserFieldID},
		Projects: []ProjectField{ProjectFieldID},
	}
	query := url.Values{}
	fields.apply(query)
	checks := map[string]string{
		"fields[users]":    "id",
		"fields[projects]": "id",
	}
	for key, want := range checks {
		if got := query.Get(key); got != want {
			t.Errorf("%s = %q, want %q", key, got, want)
		}
	}
}

// TestTimeReportListFieldsZeroValue verifies that an unset TimeReportListFields emits no
// fields[*]=… query parameters.
func TestTimeReportListFieldsZeroValue(t *testing.T) {
	var fields TimeReportListFields
	query := url.Values{}
	fields.apply(query)
	for key := range query {
		if strings.HasPrefix(key, "fields[") {
			t.Errorf("unexpected sparse-fields parameter %q on zero-value container", key)
		}
	}
}

// TestTimelogListFieldsApply verifies that populated TimelogListFields slots emit the
// expected fields[entity]=… query parameters.
func TestTimelogListFieldsApply(t *testing.T) {
	fields := TimelogListFields{
		Timelogs: []TimelogField{TimelogFieldID},
	}
	query := url.Values{}
	fields.apply(query)
	checks := map[string]string{
		"fields[timelogs]": "id",
	}
	for key, want := range checks {
		if got := query.Get(key); got != want {
			t.Errorf("%s = %q, want %q", key, got, want)
		}
	}
}

// TestTimelogListFieldsZeroValue verifies that an unset TimelogListFields emits no
// fields[*]=… query parameters.
func TestTimelogListFieldsZeroValue(t *testing.T) {
	var fields TimelogListFields
	query := url.Values{}
	fields.apply(query)
	for key := range query {
		if strings.HasPrefix(key, "fields[") {
			t.Errorf("unexpected sparse-fields parameter %q on zero-value container", key)
		}
	}
}

// TestTimerListFieldsApply verifies that populated TimerListFields slots emit the
// expected fields[entity]=… query parameters.
func TestTimerListFieldsApply(t *testing.T) {
	fields := TimerListFields{
		Timers: []TimerField{TimerFieldID},
	}
	query := url.Values{}
	fields.apply(query)
	checks := map[string]string{
		"fields[timers]": "id",
	}
	for key, want := range checks {
		if got := query.Get(key); got != want {
			t.Errorf("%s = %q, want %q", key, got, want)
		}
	}
}

// TestTimerListFieldsZeroValue verifies that an unset TimerListFields emits no
// fields[*]=… query parameters.
func TestTimerListFieldsZeroValue(t *testing.T) {
	var fields TimerListFields
	query := url.Values{}
	fields.apply(query)
	for key := range query {
		if strings.HasPrefix(key, "fields[") {
			t.Errorf("unexpected sparse-fields parameter %q on zero-value container", key)
		}
	}
}

// TestUserListFieldsApply verifies that populated UserListFields slots emit the
// expected fields[entity]=… query parameters.
func TestUserListFieldsApply(t *testing.T) {
	fields := UserListFields{
		Users: []UserField{UserFieldID},
	}
	query := url.Values{}
	fields.apply(query)
	checks := map[string]string{
		"fields[people]": "id",
	}
	for key, want := range checks {
		if got := query.Get(key); got != want {
			t.Errorf("%s = %q, want %q", key, got, want)
		}
	}
}

// TestUserListFieldsZeroValue verifies that an unset UserListFields emits no
// fields[*]=… query parameters.
func TestUserListFieldsZeroValue(t *testing.T) {
	var fields UserListFields
	query := url.Values{}
	fields.apply(query)
	for key := range query {
		if strings.HasPrefix(key, "fields[") {
			t.Errorf("unexpected sparse-fields parameter %q on zero-value container", key)
		}
	}
}

// TestWorkflowListFieldsApply verifies that populated WorkflowListFields slots emit the
// expected fields[entity]=… query parameters.
func TestWorkflowListFieldsApply(t *testing.T) {
	fields := WorkflowListFields{
		Workflows: []WorkflowField{WorkflowFieldID},
	}
	query := url.Values{}
	fields.apply(query)
	checks := map[string]string{
		"fields[workflows]": "id",
	}
	for key, want := range checks {
		if got := query.Get(key); got != want {
			t.Errorf("%s = %q, want %q", key, got, want)
		}
	}
}

// TestWorkflowListFieldsZeroValue verifies that an unset WorkflowListFields emits no
// fields[*]=… query parameters.
func TestWorkflowListFieldsZeroValue(t *testing.T) {
	var fields WorkflowListFields
	query := url.Values{}
	fields.apply(query)
	for key := range query {
		if strings.HasPrefix(key, "fields[") {
			t.Errorf("unexpected sparse-fields parameter %q on zero-value container", key)
		}
	}
}

// TestWorkflowStageListFieldsApply verifies that populated WorkflowStageListFields slots emit the
// expected fields[entity]=… query parameters.
func TestWorkflowStageListFieldsApply(t *testing.T) {
	fields := WorkflowStageListFields{
		Stages: []WorkflowStageField{WorkflowStageFieldID},
	}
	query := url.Values{}
	fields.apply(query)
	checks := map[string]string{
		"fields[stages]": "id",
	}
	for key, want := range checks {
		if got := query.Get(key); got != want {
			t.Errorf("%s = %q, want %q", key, got, want)
		}
	}
}

// TestWorkflowStageListFieldsZeroValue verifies that an unset WorkflowStageListFields emits no
// fields[*]=… query parameters.
func TestWorkflowStageListFieldsZeroValue(t *testing.T) {
	var fields WorkflowStageListFields
	query := url.Values{}
	fields.apply(query)
	for key := range query {
		if strings.HasPrefix(key, "fields[") {
			t.Errorf("unexpected sparse-fields parameter %q on zero-value container", key)
		}
	}
}
