name: 🚀 Pull Request
description: Tell us about your awesome contribution to the Teamwork Go SDK!
title: "[Feature/Fix/Docs]: "
labels: ["needs-review"]
assignees: []

body:
  - type: markdown
    attributes:
      value: |
        ## 👋 Thanks for contributing to the Teamwork Go SDK!
        
        We're excited to see what you've built! This template will help us understand your changes and get them merged faster. 
        
        **Pro tip:** The more details you provide, the quicker we can review and merge your PR! 🎯

  - type: dropdown
    id: pr-type
    attributes:
      label: 🎯 What type of change is this?
      description: Pick the one that best describes your PR (following our CONTRIBUTING.md guidelines)
      options:
        - "Feature: New functionality"
        - "Fix: Bug fixes"
        - "Docs: Documentation changes"
        - "Test: Test additions/changes"
        - "Refactor: Code refactoring"
        - "Enhancement: Improvements to existing features"
        - "Chore: Maintenance tasks"
    validations:
      required: true

  - type: textarea
    id: description
    attributes:
      label: 📋 What does this PR do?
      description: Give us the elevator pitch! What problem does this solve or what feature does it add?
      placeholder: |
        Example: "This PR adds OAuth2 refresh token support to the session package, allowing long-running applications to automatically refresh expired tokens without user intervention."
    validations:
      required: true

  - type: textarea
    id: motivation
    attributes:
      label: 🤔 Why is this change needed?
      description: Help us understand the context and motivation
      placeholder: |
        Example: "Users reported that their applications would fail after 1 hour when tokens expired. This was causing production issues for several customers who run batch processes."
    validations:
      required: true

  - type: textarea
    id: changes
    attributes:
      label: 🔨 What changes did you make?
      description: List the main changes (you can use bullet points)
      placeholder: |
        • Added `RefreshToken()` method to `OAuth2Session`
        • Implemented automatic token refresh in `makeRequest()`
        • Added new error types for token refresh failures
        • Updated examples with refresh token usage
    validations:
      required: true

  - type: textarea
    id: testing
    attributes:
      label: 🧪 How did you test this?
      description: Describe your testing strategy (see CONTRIBUTING.md for testing guidelines)
      placeholder: |
        Testing checklist:
        • Unit tests: Added/updated tests for new functionality
        • Coverage: Ran `go test -v -cover ./...` 
        • Integration: Tested with `TWAPI_SERVER=https://yourdomain.teamwork.com/ TWAPI_TOKEN=your_token go test -v ./...`
        • Linting: Verified with `golangci-lint -c .golangci.yml run ./...`
        • Manual testing: Describe any manual verification steps
        • Examples: Updated/tested relevant examples in examples/
    validations:
      required: true

  - type: checkboxes
    id: security-checklist
    attributes:
      label: 🔒 Security Considerations
      description: Please review our SECURITY.md and confirm these security aspects
      options:
        - label: My changes do not introduce security vulnerabilities
          required: true
        - label: I have not hardcoded API keys, tokens, or sensitive data
          required: true
        - label: Error handling does not expose sensitive information
          required: true
        - label: Network communications use HTTPS (enforced by SDK)
          required: false
        - label: Input validation is properly implemented for new endpoints
          required: false

  - type: checkboxes
    id: breaking-changes
    attributes:
      label: 💥 Breaking Changes
      description: Does this PR introduce any breaking changes?
      options:
        - label: This PR introduces breaking changes
          required: false
        - label: I have updated the documentation to reflect breaking changes
          required: false
        - label: I have updated the version number appropriately
          required: false

  - type: textarea
    id: breaking-details
    attributes:
      label: 💥 Breaking Change Details
      description: If you checked breaking changes above, please describe them
      placeholder: |
        Example: "The `Login()` method now returns an additional error parameter for refresh token failures. Update your error handling code."

  - type: checkboxes
    id: checklist
    attributes:
      label: ✅ Contribution Checklist
      description: Please confirm you've followed our contribution guidelines (CONTRIBUTING.md)
      options:
        - label: My code follows Go best practices and project style guidelines
          required: true
        - label: I have performed a self-review of my code
          required: true
        - label: My code has proper documentation (doc comments for exported functions/types)
          required: true
        - label: I have added tests that prove my fix/feature works
          required: false
        - label: New and existing unit tests pass locally with `go test -v ./...`
          required: true
        - label: I have run `go fmt` and `go vet` on my code
          required: true
        - label: I have updated documentation/examples as needed
          required: false
        - label: My changes generate no new warnings or errors
          required: true

  - type: checkboxes
    id: code-of-conduct
    attributes:
      label: 🤝 Community Values
      description: Please confirm you've embraced our community values (CODE_OF_CONDUCT.md)
      options:
        - label: I have been respectful and constructive in all interactions
          required: true
        - label: My contribution aligns with Teamwork's values of excellence and kindness
          required: true
        - label: I have followed the Go community's "Gopher values"
          required: true

  - type: textarea
    id: additional-context
    attributes:
      label: 📎 Additional Context
      description: Anything else we should know? Links, screenshots, related issues, etc.
      placeholder: |
        • Related to issue #123
        • Fixes compatibility with Teamwork API version X.X
        • Screenshots or examples of new functionality
        • Links to relevant Teamwork API documentation
        • Performance benchmarks (if applicable)
        • Migration notes for users (if breaking changes)
        • Special deployment or environment considerations

  - type: markdown
    attributes:
      value: |
        ---
        
        ## 🎉 Ready for Review!
        
        Thank you for contributing to the Teamwork Go SDK! Your contribution helps make project management better for teams worldwide. 🌍
        
        ### What happens next:
        
        1. **🤖 Automated checks** - Tests, linting, and security scans
        2. **👥 Code review** - Our maintainers will review following our values of kindness and excellence
        3. **💬 Collaboration** - We may ask questions or suggest improvements (all in the spirit of learning!)
        4. **🚀 Merge and celebrate** - Your code becomes part of the SDK!
        
        ### Our Review Values:
        - **🤝 We're open and trustworthy** - Transparent feedback and honest communication
        - **🔥 We're passionate** - Enthusiasm for great code and user experience  
        - **👥 Community first** - Decisions that benefit all SDK users
        - **⭐ Excellence** - High standards with patience for the learning process
        - **💙 Kindness** - Respectful, constructive, and supportive interactions
        
        Questions? Check our [CONTRIBUTING.md](CONTRIBUTING.md) or ask in the discussion! 
        
        **Thanks for making Teamwork better!** 🙌