name: Release

on:
  push:
    tags:
      - 'v*.*.*'
env:
  GO_VERSION: "1.24.x"

jobs:
  release:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v5
        with:
          persist-credentials: false
          fetch-tags: true
          fetch-depth: 0
          ref: ${{ github.ref }}

      - name: Version
        id: version
        run: |
          version="${GITHUB_REF#refs/tags/}"
          echo "version=$version" >> $GITHUB_OUTPUT

      - name: Previous Tag
        id: previous-tag
        run: |
          tag=$(git describe --tags --abbrev=0 "${GITHUB_REF}^")
          echo "tag=$tag" >> $GITHUB_OUTPUT

      - name: Create Release
        run: |
          version="${{ steps.version.outputs.version }}"
          gh release create $version \
            --fail-on-no-commits \
            --generate-notes \
            --notes-start-tag ${{ steps.previous-tag.outputs.tag }} \
            --verify-tag
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}